/* Generated by cbindgen — do not edit. */

#ifndef SWISSEPH_H
#define SWISSEPH_H

/* Generated with cbindgen:0.29.4 */

/* Warning: this file is autogenously generated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
// Opaque ephemeris handle. Created by swisseph_new(), freed by swisseph_free().
typedef struct SweEphemeris SweEphemeris;

// Error codes returned by all FFI functions. 0 = success, negative = error.
// Codes are append-only — never reorder or reassign existing values.
enum SweErrorCode
#if __STDC_VERSION__ >= 202311L
  : int32_t
#endif // __STDC_VERSION__ >= 202311L
 {
  Ok = 0,
  InvalidBody = -1,
  UnsupportedFlags = -2,
  InvalidHouseSystem = -3,
  InvalidSiderealMode = -4,
  InvalidCalendarType = -5,
  InvalidDate = -6,
  EphemerisNotAvailable = -7,
  BeyondEphemerisLimits = -8,
  FileNotFound = -9,
  FileFormat = -10,
  CircumpolarBody = -11,
  InvalidTime = -12,
  InvalidLeapSecond = -13,
  UnsupportedEphemeris = -14,
  SiderealModeRequiresFixedStars = -15,
  CError = -16,
  Panic = -90,
  InvalidArg = -91,
  Internal = -99,
};
#if __STDC_VERSION__ >= 202311L
typedef enum SweErrorCode SweErrorCode;
#else
typedef int32_t SweErrorCode;
#endif // __STDC_VERSION__ >= 202311L

// Flattened C-ABI configuration struct. Mirrors `EphemerisConfig` with C-compatible types.
//
// Use `swisseph_config_default` to initialize — a zeroed struct has WRONG defaults
// (NAN sentinels for tidal_acceleration/delta_t_userdef must be set explicitly).
typedef struct SweConfig {
  // 0 = Moshier, 1 = Swiss, 2 = Jpl.
  int32_t ephemeris_source;
  // Path to .se1 files. NULL = none.
  const char *ephe_path;
  // JPL filename (e.g. "de441.eph"). NULL = default.
  const char *jpl_filename;
  // Path to a custom leap-seconds file. NULL = use built-in table.
  const char *leap_seconds_file;
  // If true, sidereal mode is active.
  bool has_sidereal;
  // Raw swe_set_sid_mode value (bits 0-7 = mode index, upper bits = SiderealBits).
  int32_t sid_mode;
  // Reference epoch for user-defined sidereal (sid_mode & 0xFF == 255).
  double sid_t0;
  // Initial ayanamsa at sid_t0.
  double sid_ayan_t0;
  // If true, topographic position is set.
  bool has_topo;
  // Geographic longitude, degrees east-positive.
  double geolon;
  // Geographic latitude, degrees north-positive.
  double geolat;
  // Altitude above sea level, meters.
  double altitude;
  // Tidal acceleration override (arcsec/century^2). NAN = auto-derive from ephemeris.
  double tidal_acceleration;
  // User-defined Delta T (days). NAN = use models.
  double delta_t_userdef;
  // Pointer to asteroid MPC numbers. NULL + len=0 means empty.
  const int32_t *asteroid_numbers;
  // Length of asteroid_numbers array.
  uintptr_t asteroid_numbers_len;
  // Pointer to planet-moon ids. NULL + len=0 means empty.
  const int32_t *planet_moon_numbers;
  // Length of planet_moon_numbers array.
  uintptr_t planet_moon_numbers_len;
  // Pointer to extra leap-second years. NULL + len=0 means empty.
  const int32_t *extra_leap_seconds;
  // Length of extra_leap_seconds array.
  uintptr_t extra_leap_seconds_len;
  // Precession long-term model. 0 = default.
  int32_t astro_model_prec_longterm;
  // Precession short-term model. 0 = default.
  int32_t astro_model_prec_shortterm;
  // Nutation model. 0 = default.
  int32_t astro_model_nutation;
  // Frame bias model. 0 = default.
  int32_t astro_model_bias;
  // JPL Horizons mode. 0 = default.
  int32_t astro_model_jplhor;
  // JPL Horizons approx mode. 0 = default.
  int32_t astro_model_jplhora;
  // Sidereal time model. 0 = default.
  int32_t astro_model_sidereal_time;
  // Delta T model. 0 = default.
  int32_t astro_model_delta_t;
} SweConfig;

// Per-call sidereal mode override. Nullable in all FFI signatures — NULL means
// "use the handle's configured sidereal mode".
typedef struct SweSidMode {
  // Raw `swe_set_sid_mode` value (bits 0-7 = mode index, upper bits = SiderealBits).
  int32_t sid_mode;
  // Reference epoch for user-defined sidereal (mode index 255).
  double t0;
  // Initial ayanamsa at `t0`.
  double ayan_t0;
} SweSidMode;

// Return the library version as a static NUL-terminated UTF-8 string.
const char *swisseph_version(void);

// Create a new ephemeris handle from a flattened config.
//
// On success, writes the handle to `*out` and returns 0.
// On failure, returns a negative error code and writes a message to `err_buf`.
//
// # Safety
// - `config` must point to a valid `SweConfig` (use `swisseph_config_default` to initialize).
// - `out` must point to a writable `*mut SweEphemeris`.
// - `err_buf` may be NULL; if non-NULL, `err_cap` bytes must be writable.
int32_t swisseph_new(const struct SweConfig *config,
                     SweEphemeris **out,
                     char *err_buf,
                     uintptr_t err_cap);

// Free an ephemeris handle. Null-safe (no-op on NULL).
//
// # Safety
// `handle` must be NULL or a pointer previously returned by `swisseph_new` that has not
// already been freed.
void swisseph_free(SweEphemeris *handle);

// Return the resolved tidal acceleration (arcsec/century^2).
// NAN when unresolved (e.g. Moshier without explicit override).
//
// # Safety
// `handle` must be a valid, non-NULL handle from `swisseph_new`.
double swisseph_get_tid_acc(const SweEphemeris *handle);

// Write the resolved astro model values into `out` (array of 8 i32s).
// Order: prec_longterm, prec_shortterm, nutation, bias, jplhor, jplhora, sidereal_time, delta_t.
//
// # Safety
// - `handle` must be a valid, non-NULL handle from `swisseph_new`.
// - `out` must point to at least 8 writable `i32` slots.
int32_t swisseph_get_astro_models(const SweEphemeris *handle,
                                  int32_t *out,
                                  char *err_buf,
                                  uintptr_t err_cap);

// Compute planetary position at `tjd_ut` (Julian Day, UT1).
//
// # Parameters
// - `handle`: ephemeris handle from `swisseph_new`
// - `tjd_ut`: Julian Day in UT1
// - `ipl`: body number (C `ipl` values, matching `Body` discriminant)
// - `iflag`: calculation flags (C `SEFLG_*` bit values)
// - `geopos`: NULL, or pointer to `[lon, lat, alt]` for a per-call topographic override
// - `sid_mode`: NULL, or pointer to a `SweSidMode` for a per-call sidereal override
// - `xx`: out-param, pointer to 6 `f64` slots receiving [lon, lat, dist, lon_speed, lat_speed, dist_speed]
// - `flags_used`: out-param (may be NULL), pointer to `i32` receiving the flags actually applied
// - `err_buf`, `err_cap`: optional error message buffer
//
// Returns 0 on success, negative error code on failure.
//
// # Safety
// - `handle` must be a valid, non-NULL handle.
// - `xx` must point to at least 6 writable `f64` slots.
// - `geopos`, if non-NULL, must point to 3 readable `f64` values.
int32_t swisseph_calc_ut(const SweEphemeris *handle,
                         double tjd_ut,
                         int32_t ipl,
                         int32_t iflag,
                         const double *geopos,
                         const struct SweSidMode *sid_mode,
                         double *xx,
                         int32_t *flags_used,
                         char *err_buf,
                         uintptr_t err_cap);

// Compute planetary position at `tjd_et` (Julian Day, TT/ET).
// Same as `swisseph_calc_ut` but takes Terrestrial Time directly.
//
// # Safety
// Same as `swisseph_calc_ut`.
int32_t swisseph_calc(const SweEphemeris *handle,
                      double tjd_et,
                      int32_t ipl,
                      int32_t iflag,
                      const double *geopos,
                      const struct SweSidMode *sid_mode,
                      double *xx,
                      int32_t *flags_used,
                      char *err_buf,
                      uintptr_t err_cap);

// Compute planetocentric position at `tjd_et` (TT).
// Swiss/JPL only — Moshier returns an error.
//
// # Parameters
// - `ipl`: target body
// - `iplctr`: center body (must differ from `ipl`)
// - No `geopos` override (C's `swe_calc_pctr` has no topocentric path)
//
// # Safety
// - `handle` must be a valid, non-NULL handle.
// - `xx` must point to at least 6 writable `f64` slots.
int32_t swisseph_calc_pctr(const SweEphemeris *handle,
                           double tjd_et,
                           int32_t ipl,
                           int32_t iplctr,
                           int32_t iflag,
                           double *xx,
                           int32_t *flags_used,
                           char *err_buf,
                           uintptr_t err_cap);

// Compute fixed-star position at `tjd_et` (TT).
//
// # Parameters
// - `star`: input star name (NUL-terminated UTF-8)
// - `star_out`: buffer receiving the resolved "name,bayer" canonical name (NUL-terminated)
// - `star_out_cap`: capacity of `star_out` in bytes (including NUL)
// - `geopos`: NULL, or `[lon, lat, alt]` for per-call topographic override
// - `sid_mode`: NULL, or per-call sidereal override
// - `xx`: out-param, 6 `f64` slots
// - `flags_used`: out-param (may be NULL)
//
// # Safety
// - `star` must be a valid NUL-terminated UTF-8 string.
// - `star_out` may be NULL; if non-NULL, `star_out_cap` bytes must be writable.
// - `xx` must point to at least 6 writable `f64` slots.
int32_t swisseph_fixstar2(const SweEphemeris *handle,
                          const char *star,
                          char *star_out,
                          uintptr_t star_out_cap,
                          double tjd_et,
                          int32_t iflag,
                          const double *geopos,
                          const struct SweSidMode *sid_mode,
                          double *xx,
                          int32_t *flags_used,
                          char *err_buf,
                          uintptr_t err_cap);

// Compute fixed-star position at `tjd_ut` (UT1).
// Same as `swisseph_fixstar2` but takes Universal Time.
//
// # Safety
// Same as `swisseph_fixstar2`.
int32_t swisseph_fixstar2_ut(const SweEphemeris *handle,
                             const char *star,
                             char *star_out,
                             uintptr_t star_out_cap,
                             double tjd_ut,
                             int32_t iflag,
                             const double *geopos,
                             const struct SweSidMode *sid_mode,
                             double *xx,
                             int32_t *flags_used,
                             char *err_buf,
                             uintptr_t err_cap);

// Look up the magnitude of a fixed star by name.
//
// # Parameters
// - `star`: input star name (NUL-terminated UTF-8)
// - `star_out`: buffer receiving the resolved canonical name (may be NULL)
// - `star_out_cap`: capacity of `star_out`
// - `mag`: out-param receiving the magnitude
//
// # Safety
// - `star` must be a valid NUL-terminated UTF-8 string.
// - `mag` must point to a writable `f64`.
int32_t swisseph_fixstar2_mag(const SweEphemeris *handle,
                              const char *star,
                              char *star_out,
                              uintptr_t star_out_cap,
                              double *mag,
                              char *err_buf,
                              uintptr_t err_cap);

// Ayanamsa at `tjd_et` (TT) with flags. Nutation added unless `NONUT` is set.
//
// # Parameters
// - `sid_mode`: NULL uses the handle's configured sidereal mode; non-NULL overrides per-call
// - `daya`: out-param receiving the ayanamsa in degrees
// - `flags_used`: out-param (may be NULL)
//
// Returns 0 on success, negative error code on failure.
//
// # Safety
// - `handle` must be valid, non-NULL.
// - `daya` must point to a writable `f64`.
int32_t swisseph_get_ayanamsa_ex(const SweEphemeris *handle,
                                 double tjd_et,
                                 int32_t iflag,
                                 const struct SweSidMode *sid_mode,
                                 double *daya,
                                 int32_t *flags_used,
                                 char *err_buf,
                                 uintptr_t err_cap);

// Ayanamsa at `tjd_ut` (UT1) with flags. Nutation added unless `NONUT` is set.
//
// # Safety
// Same as `swisseph_get_ayanamsa_ex`.
int32_t swisseph_get_ayanamsa_ex_ut(const SweEphemeris *handle,
                                    double tjd_ut,
                                    int32_t iflag,
                                    const struct SweSidMode *sid_mode,
                                    double *daya,
                                    int32_t *flags_used,
                                    char *err_buf,
                                    uintptr_t err_cap);

// Legacy ayanamsa at `tjd_et` (TT), no nutation, returns degrees directly.
// Returns NAN on error (e.g. no sidereal mode configured and no per-call override).
//
// # Safety
// `handle` must be valid, non-NULL.
double swisseph_get_ayanamsa(const SweEphemeris *handle,
                             double tjd_et,
                             const struct SweSidMode *sid_mode);

// Legacy ayanamsa at `tjd_ut` (UT1), no nutation, returns degrees directly.
// Returns NAN on error.
//
// # Safety
// `handle` must be valid, non-NULL.
double swisseph_get_ayanamsa_ut(const SweEphemeris *handle,
                                double tjd_ut,
                                const struct SweSidMode *sid_mode);

// Write the human-readable name for a sidereal mode into `buf`.
// User-defined mode (255) writes an empty string. Unknown mode returns an error.
//
// Handle-free — does not require an ephemeris instance.
//
// # Safety
// - `buf` must point to at least `cap` writable bytes, or be NULL (returns error).
int32_t swisseph_get_ayanamsa_name(int32_t sid_mode_raw,
                                   char *buf,
                                   uintptr_t cap,
                                   char *err_buf,
                                   uintptr_t err_cap);

// Write the display name for a body into `buf` (e.g. "Sun", "Chiron", asteroid name).
//
// # Safety
// - `handle` must be valid, non-NULL.
// - `buf` must point to at least `cap` writable bytes.
int32_t swisseph_get_planet_name(const SweEphemeris *handle,
                                 int32_t ipl,
                                 char *buf,
                                 uintptr_t cap,
                                 char *err_buf,
                                 uintptr_t err_cap);

// Fill a SweConfig with sane defaults (Moshier, no paths, NAN for unset scalars).
//
// # Safety
// `config` must point to a valid, writable `SweConfig`.
void swisseph_config_default(struct SweConfig *config);

#endif  /* SWISSEPH_H */
