/* Generated by cbindgen — do not edit. */

#ifndef SWISSEPH_H
#define SWISSEPH_H

/* Generated with cbindgen:0.29.4 */

/* Warning: this file is autogenously generated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
// Opaque ephemeris handle. Created by swisseph_new(), freed by swisseph_free().
typedef struct SweEphemeris SweEphemeris;

// Error codes returned by all FFI functions. 0 = success, negative = error.
// Codes are append-only — never reorder or reassign existing values.
enum SweErrorCode
#if __STDC_VERSION__ >= 202311L
  : int32_t
#endif // __STDC_VERSION__ >= 202311L
 {
  Ok = 0,
  InvalidBody = -1,
  UnsupportedFlags = -2,
  InvalidHouseSystem = -3,
  InvalidSiderealMode = -4,
  InvalidCalendarType = -5,
  InvalidDate = -6,
  EphemerisNotAvailable = -7,
  BeyondEphemerisLimits = -8,
  FileNotFound = -9,
  FileFormat = -10,
  CircumpolarBody = -11,
  InvalidTime = -12,
  InvalidLeapSecond = -13,
  UnsupportedEphemeris = -14,
  SiderealModeRequiresFixedStars = -15,
  CError = -16,
  Panic = -90,
  InvalidArg = -91,
  Internal = -99,
};
#if __STDC_VERSION__ >= 202311L
typedef enum SweErrorCode SweErrorCode;
#else
typedef int32_t SweErrorCode;
#endif // __STDC_VERSION__ >= 202311L

// Flattened C-ABI configuration struct. Mirrors `EphemerisConfig` with C-compatible types.
//
// Use `swisseph_config_default` to initialize — a zeroed struct has WRONG defaults
// (NAN sentinels for tidal_acceleration/delta_t_userdef must be set explicitly).
typedef struct SweConfig {
  // 0 = Moshier, 1 = Swiss, 2 = Jpl.
  int32_t ephemeris_source;
  // Path to .se1 files. NULL = none.
  const char *ephe_path;
  // JPL filename (e.g. "de441.eph"). NULL = default.
  const char *jpl_filename;
  // Path to a custom leap-seconds file. NULL = use built-in table.
  const char *leap_seconds_file;
  // If true, sidereal mode is active.
  bool has_sidereal;
  // Raw swe_set_sid_mode value (bits 0-7 = mode index, upper bits = SiderealBits).
  int32_t sid_mode;
  // Reference epoch for user-defined sidereal (sid_mode & 0xFF == 255).
  double sid_t0;
  // Initial ayanamsa at sid_t0.
  double sid_ayan_t0;
  // If true, topographic position is set.
  bool has_topo;
  // Geographic longitude, degrees east-positive.
  double geolon;
  // Geographic latitude, degrees north-positive.
  double geolat;
  // Altitude above sea level, meters.
  double altitude;
  // Tidal acceleration override (arcsec/century^2). NAN = auto-derive from ephemeris.
  double tidal_acceleration;
  // User-defined Delta T (days). NAN = use models.
  double delta_t_userdef;
  // Pointer to asteroid MPC numbers. NULL + len=0 means empty.
  const int32_t *asteroid_numbers;
  // Length of asteroid_numbers array.
  uintptr_t asteroid_numbers_len;
  // Pointer to planet-moon ids. NULL + len=0 means empty.
  const int32_t *planet_moon_numbers;
  // Length of planet_moon_numbers array.
  uintptr_t planet_moon_numbers_len;
  // Pointer to extra leap-second years. NULL + len=0 means empty.
  const int32_t *extra_leap_seconds;
  // Length of extra_leap_seconds array.
  uintptr_t extra_leap_seconds_len;
  // Precession long-term model. 0 = default.
  int32_t astro_model_prec_longterm;
  // Precession short-term model. 0 = default.
  int32_t astro_model_prec_shortterm;
  // Nutation model. 0 = default.
  int32_t astro_model_nutation;
  // Frame bias model. 0 = default.
  int32_t astro_model_bias;
  // JPL Horizons mode. 0 = default.
  int32_t astro_model_jplhor;
  // JPL Horizons approx mode. 0 = default.
  int32_t astro_model_jplhora;
  // Sidereal time model. 0 = default.
  int32_t astro_model_sidereal_time;
  // Delta T model. 0 = default.
  int32_t astro_model_delta_t;
} SweConfig;

// Per-call sidereal mode override. Nullable in all FFI signatures — NULL means
// "use the handle's configured sidereal mode".
typedef struct SweSidMode {
  // Raw `swe_set_sid_mode` value (bits 0-7 = mode index, upper bits = SiderealBits).
  int32_t sid_mode;
  // Reference epoch for user-defined sidereal (mode index 255).
  double t0;
  // Initial ayanamsa at `t0`.
  double ayan_t0;
} SweSidMode;

// Return the library version as a static NUL-terminated UTF-8 string.
const char *swisseph_version(void);

// Create a new ephemeris handle from a flattened config.
//
// On success, writes the handle to `*out` and returns 0.
// On failure, returns a negative error code and writes a message to `err_buf`.
//
// # Safety
// - `config` must point to a valid `SweConfig` (use `swisseph_config_default` to initialize).
// - `out` must point to a writable `*mut SweEphemeris`.
// - `err_buf` may be NULL; if non-NULL, `err_cap` bytes must be writable.
int32_t swisseph_new(const struct SweConfig *config,
                     SweEphemeris **out,
                     char *err_buf,
                     uintptr_t err_cap);

// Free an ephemeris handle. Null-safe (no-op on NULL).
//
// # Safety
// `handle` must be NULL or a pointer previously returned by `swisseph_new` that has not
// already been freed.
void swisseph_free(SweEphemeris *handle);

// Return the resolved tidal acceleration (arcsec/century^2).
// NAN when unresolved (e.g. Moshier without explicit override).
//
// # Safety
// `handle` must be a valid, non-NULL handle from `swisseph_new`.
double swisseph_get_tid_acc(const SweEphemeris *handle);

// Write the resolved astro model values into `out` (array of 8 i32s).
// Order: prec_longterm, prec_shortterm, nutation, bias, jplhor, jplhora, sidereal_time, delta_t.
//
// # Safety
// - `handle` must be a valid, non-NULL handle from `swisseph_new`.
// - `out` must point to at least 8 writable `i32` slots.
int32_t swisseph_get_astro_models(const SweEphemeris *handle,
                                  int32_t *out,
                                  char *err_buf,
                                  uintptr_t err_cap);

// Compute planetary position at `tjd_ut` (Julian Day, UT1).
//
// # Parameters
// - `handle`: ephemeris handle from `swisseph_new`
// - `tjd_ut`: Julian Day in UT1
// - `ipl`: body number (C `ipl` values, matching `Body` discriminant)
// - `iflag`: calculation flags (C `SEFLG_*` bit values)
// - `geopos`: NULL, or pointer to `[lon, lat, alt]` for a per-call topographic override
// - `sid_mode`: NULL, or pointer to a `SweSidMode` for a per-call sidereal override
// - `xx`: out-param, pointer to 6 `f64` slots receiving [lon, lat, dist, lon_speed, lat_speed, dist_speed]
// - `flags_used`: out-param (may be NULL), pointer to `i32` receiving the flags actually applied
// - `err_buf`, `err_cap`: optional error message buffer
//
// Returns 0 on success, negative error code on failure.
//
// # Safety
// - `handle` must be a valid, non-NULL handle.
// - `xx` must point to at least 6 writable `f64` slots.
// - `geopos`, if non-NULL, must point to 3 readable `f64` values.
int32_t swisseph_calc_ut(const SweEphemeris *handle,
                         double tjd_ut,
                         int32_t ipl,
                         int32_t iflag,
                         const double *geopos,
                         const struct SweSidMode *sid_mode,
                         double *xx,
                         int32_t *flags_used,
                         char *err_buf,
                         uintptr_t err_cap);

// Compute planetary position at `tjd_et` (Julian Day, TT/ET).
//
// # Parameters
// - `handle`: ephemeris handle from `swisseph_new`
// - `tjd_et`: Julian Day in TT/ET
// - `ipl`: body number (C `ipl` values, matching `Body` discriminant)
// - `iflag`: calculation flags (C `SEFLG_*` bit values)
// - `geopos`: NULL, or pointer to `[lon, lat, alt]` for a per-call topographic override
// - `sid_mode`: NULL, or pointer to a `SweSidMode` for a per-call sidereal override
// - `xx`: out-param, pointer to 6 `f64` slots receiving [lon, lat, dist, lon_speed, lat_speed, dist_speed]
// - `flags_used`: out-param (may be NULL), pointer to `i32` receiving the flags actually applied
// - `err_buf`, `err_cap`: optional error message buffer
//
// Returns 0 on success, negative error code on failure.
//
// # Safety
// - `handle` must be a valid, non-NULL handle.
// - `xx` must point to at least 6 writable `f64` slots.
// - `geopos`, if non-NULL, must point to 3 readable `f64` values.
int32_t swisseph_calc(const SweEphemeris *handle,
                      double tjd_et,
                      int32_t ipl,
                      int32_t iflag,
                      const double *geopos,
                      const struct SweSidMode *sid_mode,
                      double *xx,
                      int32_t *flags_used,
                      char *err_buf,
                      uintptr_t err_cap);

// Compute planetocentric position at `tjd_et` (TT).
// Swiss/JPL only — Moshier returns an error.
//
// # Parameters
// - `ipl`: target body
// - `iplctr`: center body (must differ from `ipl`)
// - No `geopos` override (C's `swe_calc_pctr` has no topocentric path)
//
// # Safety
// - `handle` must be a valid, non-NULL handle.
// - `xx` must point to at least 6 writable `f64` slots.
int32_t swisseph_calc_pctr(const SweEphemeris *handle,
                           double tjd_et,
                           int32_t ipl,
                           int32_t iplctr,
                           int32_t iflag,
                           double *xx,
                           int32_t *flags_used,
                           char *err_buf,
                           uintptr_t err_cap);

// Compute fixed-star position at `tjd_et` (TT).
//
// # Parameters
// - `star`: input star name (NUL-terminated UTF-8)
// - `star_out`: buffer receiving the resolved "name,bayer" canonical name (NUL-terminated)
// - `star_out_cap`: capacity of `star_out` in bytes (including NUL)
// - `geopos`: NULL, or `[lon, lat, alt]` for per-call topographic override
// - `sid_mode`: NULL, or per-call sidereal override
// - `xx`: out-param, 6 `f64` slots
// - `flags_used`: out-param (may be NULL)
//
// # Safety
// - `star` must be a valid NUL-terminated UTF-8 string.
// - `star_out` may be NULL; if non-NULL, `star_out_cap` bytes must be writable.
// - `xx` must point to at least 6 writable `f64` slots.
int32_t swisseph_fixstar2(const SweEphemeris *handle,
                          const char *star,
                          char *star_out,
                          uintptr_t star_out_cap,
                          double tjd_et,
                          int32_t iflag,
                          const double *geopos,
                          const struct SweSidMode *sid_mode,
                          double *xx,
                          int32_t *flags_used,
                          char *err_buf,
                          uintptr_t err_cap);

// Compute fixed-star position at `tjd_ut` (UT1).
//
// # Parameters
// - `star`: input star name (NUL-terminated UTF-8)
// - `star_out`: buffer receiving the resolved "name,bayer" canonical name (NUL-terminated);
//   may be NULL if the resolved name is not needed
// - `star_out_cap`: capacity of `star_out` in bytes (including NUL)
// - `geopos`: NULL, or `[lon, lat, alt]` for per-call topographic override
// - `sid_mode`: NULL, or per-call sidereal override
// - `xx`: out-param, pointer to 6 `f64` slots
// - `flags_used`: out-param (may be NULL)
//
// Returns 0 on success, negative error code on failure.
//
// # Safety
// - `star` must be a valid NUL-terminated UTF-8 string.
// - `star_out` may be NULL; if non-NULL, `star_out_cap` bytes must be writable.
// - `xx` must point to at least 6 writable `f64` slots.
int32_t swisseph_fixstar2_ut(const SweEphemeris *handle,
                             const char *star,
                             char *star_out,
                             uintptr_t star_out_cap,
                             double tjd_ut,
                             int32_t iflag,
                             const double *geopos,
                             const struct SweSidMode *sid_mode,
                             double *xx,
                             int32_t *flags_used,
                             char *err_buf,
                             uintptr_t err_cap);

// Look up the magnitude of a fixed star by name.
//
// # Parameters
// - `star`: input star name (NUL-terminated UTF-8)
// - `star_out`: buffer receiving the resolved canonical name (may be NULL)
// - `star_out_cap`: capacity of `star_out`
// - `mag`: out-param receiving the magnitude
//
// # Safety
// - `star` must be a valid NUL-terminated UTF-8 string.
// - `mag` must point to a writable `f64`.
int32_t swisseph_fixstar2_mag(const SweEphemeris *handle,
                              const char *star,
                              char *star_out,
                              uintptr_t star_out_cap,
                              double *mag,
                              char *err_buf,
                              uintptr_t err_cap);

// Ayanamsa at `tjd_et` (TT) with flags. Nutation added unless `NONUT` is set.
//
// # Parameters
// - `sid_mode`: NULL uses the handle's configured sidereal mode; non-NULL overrides per-call
// - `daya`: out-param receiving the ayanamsa in degrees
// - `flags_used`: out-param (may be NULL)
//
// Returns 0 on success, negative error code on failure.
//
// # Safety
// - `handle` must be valid, non-NULL.
// - `daya` must point to a writable `f64`.
int32_t swisseph_get_ayanamsa_ex(const SweEphemeris *handle,
                                 double tjd_et,
                                 int32_t iflag,
                                 const struct SweSidMode *sid_mode,
                                 double *daya,
                                 int32_t *flags_used,
                                 char *err_buf,
                                 uintptr_t err_cap);

// Ayanamsa at `tjd_ut` (UT1) with flags. Nutation added unless `NONUT` is set.
//
// # Parameters
// - `sid_mode`: NULL uses the handle's configured sidereal mode; non-NULL overrides per-call
// - `daya`: out-param receiving the ayanamsa in degrees
// - `flags_used`: out-param (may be NULL)
//
// Returns 0 on success, negative error code on failure.
//
// # Safety
// - `handle` must be valid, non-NULL.
// - `daya` must point to a writable `f64`.
int32_t swisseph_get_ayanamsa_ex_ut(const SweEphemeris *handle,
                                    double tjd_ut,
                                    int32_t iflag,
                                    const struct SweSidMode *sid_mode,
                                    double *daya,
                                    int32_t *flags_used,
                                    char *err_buf,
                                    uintptr_t err_cap);

// Legacy ayanamsa at `tjd_et` (TT), no nutation, returns degrees directly.
// Returns NAN on error (e.g. no sidereal mode configured and no per-call override).
//
// # Safety
// `handle` must be valid, non-NULL.
double swisseph_get_ayanamsa(const SweEphemeris *handle,
                             double tjd_et,
                             const struct SweSidMode *sid_mode);

// Legacy ayanamsa at `tjd_ut` (UT1), no nutation, returns degrees directly.
// Returns NAN on error.
//
// # Safety
// `handle` must be valid, non-NULL.
double swisseph_get_ayanamsa_ut(const SweEphemeris *handle,
                                double tjd_ut,
                                const struct SweSidMode *sid_mode);

// Write the human-readable name for a sidereal mode into `buf`.
// User-defined mode (255) writes an empty string. Unknown mode returns an error.
//
// Handle-free — does not require an ephemeris instance.
//
// # Safety
// - `buf` must point to at least `cap` writable bytes, or be NULL (returns error).
int32_t swisseph_get_ayanamsa_name(int32_t sid_mode_raw,
                                   char *buf,
                                   uintptr_t cap,
                                   char *err_buf,
                                   uintptr_t err_cap);

// Write the display name for a body into `buf` (e.g. "Sun", "Chiron", asteroid name).
//
// # Safety
// - `handle` must be valid, non-NULL.
// - `buf` must point to at least `cap` writable bytes.
int32_t swisseph_get_planet_name(const SweEphemeris *handle,
                                 int32_t ipl,
                                 char *buf,
                                 uintptr_t cap,
                                 char *err_buf,
                                 uintptr_t err_cap);

// Fill a SweConfig with sane defaults (Moshier, no paths, NAN for unset scalars).
//
// # Safety
// `config` must point to a valid, writable `SweConfig`.
void swisseph_config_default(struct SweConfig *config);

// Convert a calendar date + fractional hour (UT) to a Julian Day number.
// `gregflag`: 0 = Julian calendar, 1 = Gregorian calendar.
//
// # Safety
// No pointer arguments.
double swisseph_julday(int32_t year, int32_t month, int32_t day, double hour, int32_t gregflag);

// Convert a Julian Day number to calendar date components.
// `gregflag`: 0 = Julian calendar, 1 = Gregorian calendar.
//
// # Safety
// - `year`, `month`, `day` must point to writable `i32` slots.
// - `hour` must point to a writable `f64`.
void swisseph_revjul(double jd,
                     int32_t gregflag,
                     int32_t *year,
                     int32_t *month,
                     int32_t *day,
                     double *hour);

// Validate and convert a calendar date to a Julian Day.
// Returns 0 on success (writes JD to `*tjd`), or ERR on invalid date.
// `cal`: 'g'/'G' = Gregorian, 'j'/'J' = Julian.
//
// # Safety
// - `tjd` must point to a writable `f64`.
int32_t swisseph_date_conversion(int32_t year,
                                 int32_t month,
                                 int32_t day,
                                 double hour,
                                 char cal,
                                 double *tjd,
                                 char *err_buf,
                                 uintptr_t err_cap);

// Day of the week for a Julian Day: 0 = Monday .. 6 = Sunday.
//
// # Safety
// No pointer arguments.
int32_t swisseph_day_of_week(double jd);

// Shift a UTC date/time by a timezone offset (hours, east positive).
// All time components are both input and output (in-place conversion).
//
// # Safety
// - All pointer arguments must point to writable locations.
void swisseph_utc_time_zone(int32_t iyear,
                            int32_t imonth,
                            int32_t iday,
                            int32_t ihour,
                            int32_t imin,
                            double dsec,
                            double d_timezone,
                            int32_t *oyear,
                            int32_t *omonth,
                            int32_t *oday,
                            int32_t *ohour,
                            int32_t *omin,
                            double *osec);

// Convert UTC to Julian Day (TT and UT1). Writes `dret[0]` = JD(TT), `dret[1]` = JD(UT1).
// `gregflag`: 0 = Julian, 1 = Gregorian.
//
// # Safety
// - `handle` must be a valid, non-NULL handle.
// - `dret` must point to at least 2 writable `f64` slots.
int32_t swisseph_utc_to_jd(const SweEphemeris *handle,
                           int32_t year,
                           int32_t month,
                           int32_t day,
                           int32_t hour,
                           int32_t min,
                           double sec,
                           int32_t gregflag,
                           double *dret,
                           char *err_buf,
                           uintptr_t err_cap);

// Convert Julian Day (TT) to UTC calendar components.
// `gregflag`: 0 = Julian, 1 = Gregorian.
//
// # Safety
// - `handle` must be a valid, non-NULL handle.
// - All out-param pointers must be writable.
void swisseph_jdet_to_utc(const SweEphemeris *handle,
                          double tjd_et,
                          int32_t gregflag,
                          int32_t *year,
                          int32_t *month,
                          int32_t *day,
                          int32_t *hour,
                          int32_t *min,
                          double *sec);

// Convert Julian Day (UT1) to UTC calendar components.
// `gregflag`: 0 = Julian, 1 = Gregorian.
//
// # Safety
// - `handle` must be a valid, non-NULL handle.
// - All out-param pointers must be writable.
void swisseph_jdut1_to_utc(const SweEphemeris *handle,
                           double tjd_ut,
                           int32_t gregflag,
                           int32_t *year,
                           int32_t *month,
                           int32_t *day,
                           int32_t *hour,
                           int32_t *min,
                           double *sec);

// Compute Delta T (TT - UT1) in days for `tjd_ut`.
// Uses the handle's configured ephemeris model.
//
// # Safety
// `handle` must be a valid, non-NULL handle.
double swisseph_deltat(const SweEphemeris *handle, double tjd_ut);

// Compute Delta T (TT - UT1) in days for `tjd_ut`, with iflag-based ephemeris resolution.
// Writes the result to `*deltat`. Returns 0 on success.
//
// The `iflag` EPHMASK bits select which ephemeris backend's tidal acceleration to use.
//
// # Safety
// - `handle` must be valid, non-NULL.
// - `deltat` must point to a writable `f64`.
int32_t swisseph_deltat_ex(const SweEphemeris *handle,
                           double tjd_ut,
                           int32_t iflag,
                           double *deltat,
                           char *err_buf,
                           uintptr_t err_cap);

// Greenwich Apparent Sidereal Time (hours, 0..24) from `tjd_ut`.
// Uses the handle's configured astro models. Forces TIDAL_DEFAULT internally
// (matching C's `swe_sidtime` behavior).
//
// # Safety
// `handle` must be valid, non-NULL.
double swisseph_sidtime(const SweEphemeris *handle, double tjd_ut);

// Greenwich Apparent Sidereal Time (hours, 0..24) from pre-computed
// true obliquity `eps` (degrees) and nutation in longitude `nut` (degrees).
// Forces TIDAL_DEFAULT internally (matching C's `swe_sidtime0` behavior).
//
// # Safety
// `handle` must be valid, non-NULL.
double swisseph_sidtime0(const SweEphemeris *handle, double tjd_ut, double eps, double nut);

// Equation of time at `tjd_ut` (UT1). Returns `E = LAT − LMT` in **days**.
// Positive means the Sun is ahead of the mean Sun.
//
// # Safety
// - `handle` must be valid, non-NULL.
// - `e` must point to a writable `f64`.
int32_t swisseph_time_equ(const SweEphemeris *handle,
                          double tjd_ut,
                          double *e,
                          char *err_buf,
                          uintptr_t err_cap);

// Convert Local Mean Time to Local Apparent Time.
// `geolon` in degrees (east-positive). `tjd_lmt` and output are Julian Day (UT-scale).
//
// # Safety
// - `handle` must be valid, non-NULL.
// - `tjd_lat` must point to a writable `f64`.
int32_t swisseph_lmt_to_lat(const SweEphemeris *handle,
                            double tjd_lmt,
                            double geolon,
                            double *tjd_lat,
                            char *err_buf,
                            uintptr_t err_cap);

// Convert Local Apparent Time to Local Mean Time.
// `geolon` in degrees (east-positive). `tjd_lat` and output are Julian Day (UT-scale).
//
// # Safety
// - `handle` must be valid, non-NULL.
// - `tjd_lmt` must point to a writable `f64`.
int32_t swisseph_lat_to_lmt(const SweEphemeris *handle,
                            double tjd_lat,
                            double geolon,
                            double *tjd_lmt,
                            char *err_buf,
                            uintptr_t err_cap);

// Round centiseconds to the nearest arcsecond with a 30°-boundary guard.
//
// # Safety
// No pointer arguments.
int32_t swisseph_csroundsec(int32_t x);

// Format time-of-day centiseconds as `"HH:MM:SS"` into `buf`.
// `sep` is the separator character (e.g. ':').
// `suppress_zero`: if true, omits seconds when they are zero.
//
// # Safety
// - `buf` must point to at least `cap` writable bytes.
void swisseph_cs2timestr(int32_t t, char sep, bool suppress_zero, char *buf, uintptr_t cap);

// Format arc centiseconds as a longitude/latitude string with direction letters.
// `pchar` for positive, `mchar` for negative.
//
// # Safety
// - `buf` must point to at least `cap` writable bytes.
void swisseph_cs2lonlatstr(int32_t t, char pchar, char mchar, char *buf, uintptr_t cap);

// Format arc centiseconds as degrees-within-sign (`" D°MM'SS"`).
// Truncates (no rounding) and wraps into [0, 30°).
//
// # Safety
// - `buf` must point to at least `cap` writable bytes.
void swisseph_cs2degstr(int32_t t, char *buf, uintptr_t cap);

// Split a decimal degree value into components. Mirrors C's `swe_split_deg`.
//
// # Parameters
// - `ddeg`: decimal degrees to split
// - `roundflag`: combination of SE_SPLIT_DEG_* flags
// - `deg`, `min`, `sec`: out-params for integer components
// - `secfr`: out-param for fractional seconds
// - `sign`: out-param for sign (zodiacal sign index, or ±1)
//
// # Safety
// All out-param pointers must be writable.
void swisseph_split_deg(double ddeg,
                        int32_t roundflag,
                        int32_t *deg,
                        int32_t *min,
                        int32_t *sec,
                        double *secfr,
                        int32_t *sign);

// Normalize degrees to [0, 360). Port of `swe_degnorm`.
double swisseph_degnorm(double x);

// Normalize radians to [0, 2π). Port of `swe_radnorm`.
double swisseph_radnorm(double x);

// Difference `p1 - p2` normalized to [0, 360). Port of `swe_difdegn`.
double swisseph_difdegn(double p1, double p2);

// Difference `p1 - p2` normalized to (-180, 180]. Port of `swe_difdeg2n`.
double swisseph_difdeg2n(double p1, double p2);

// Midpoint of two degree values on the 360° circle. Port of `swe_deg_midp`.
double swisseph_deg_midp(double x1, double x0);

// Midpoint of two radian values on the 2π circle. Port of `swe_rad_midp`.
double swisseph_rad_midp(double x1, double x0);

// Coordinate transformation (ecliptic ↔ equatorial).
// `xpo[3]` in, `xpn[3]` out. `eps` in degrees.
//
// # Safety
// - `xpo` must point to 3 readable `f64` values.
// - `xpn` must point to 3 writable `f64` values.
void swisseph_cotrans(const double *xpo, double *xpn, double eps);

// Coordinate transformation with speed (ecliptic ↔ equatorial).
// `xpo[6]` in (pos + speed), `xpn[6]` out. `eps` in degrees.
//
// # Safety
// - `xpo` must point to 6 readable `f64` values.
// - `xpn` must point to 6 writable `f64` values.
void swisseph_cotrans_sp(const double *xpo, double *xpn, double eps);

#endif  /* SWISSEPH_H */
