/* Generated by cbindgen — do not edit. */

#ifndef SWISSEPH_H
#define SWISSEPH_H

/* Generated with cbindgen:0.29.4 */

/* Warning: this file is autogenously generated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
// Opaque ephemeris handle. Created by swisseph_new(), freed by swisseph_free().
typedef struct SweEphemeris SweEphemeris;

// Error codes returned by all FFI functions. 0 = success, negative = error.
// Codes are append-only — never reorder or reassign existing values.
enum SweErrorCode
#if __STDC_VERSION__ >= 202311L
  : int32_t
#endif // __STDC_VERSION__ >= 202311L
 {
  Ok = 0,
  InvalidBody = -1,
  UnsupportedFlags = -2,
  InvalidHouseSystem = -3,
  InvalidSiderealMode = -4,
  InvalidCalendarType = -5,
  InvalidDate = -6,
  EphemerisNotAvailable = -7,
  BeyondEphemerisLimits = -8,
  FileNotFound = -9,
  FileFormat = -10,
  CircumpolarBody = -11,
  InvalidTime = -12,
  InvalidLeapSecond = -13,
  UnsupportedEphemeris = -14,
  SiderealModeRequiresFixedStars = -15,
  CError = -16,
  Panic = -90,
  InvalidArg = -91,
  Internal = -99,
};
#if __STDC_VERSION__ >= 202311L
typedef enum SweErrorCode SweErrorCode;
#else
typedef int32_t SweErrorCode;
#endif // __STDC_VERSION__ >= 202311L

// Flattened C-ABI configuration struct. Mirrors `EphemerisConfig` with C-compatible types.
//
// Use `swisseph_config_default` to initialize — a zeroed struct has WRONG defaults
// (NAN sentinels for tidal_acceleration/delta_t_userdef must be set explicitly).
typedef struct SweConfig {
  // 0 = Moshier, 1 = Swiss, 2 = Jpl.
  int32_t ephemeris_source;
  // Path to .se1 files. NULL = none.
  const char *ephe_path;
  // JPL filename (e.g. "de441.eph"). NULL = default.
  const char *jpl_filename;
  // Path to a custom leap-seconds file. NULL = use built-in table.
  const char *leap_seconds_file;
  // If true, sidereal mode is active.
  bool has_sidereal;
  // Raw swe_set_sid_mode value (bits 0-7 = mode index, upper bits = SiderealBits).
  int32_t sid_mode;
  // Reference epoch for user-defined sidereal (sid_mode & 0xFF == 255).
  double sid_t0;
  // Initial ayanamsa at sid_t0.
  double sid_ayan_t0;
  // If true, topographic position is set.
  bool has_topo;
  // Geographic longitude, degrees east-positive.
  double geolon;
  // Geographic latitude, degrees north-positive.
  double geolat;
  // Altitude above sea level, meters.
  double altitude;
  // Tidal acceleration override (arcsec/century^2). NAN = auto-derive from ephemeris.
  double tidal_acceleration;
  // User-defined Delta T (days). NAN = use models.
  double delta_t_userdef;
  // Pointer to asteroid MPC numbers. NULL + len=0 means empty.
  const int32_t *asteroid_numbers;
  // Length of asteroid_numbers array.
  uintptr_t asteroid_numbers_len;
  // Pointer to planet-moon ids. NULL + len=0 means empty.
  const int32_t *planet_moon_numbers;
  // Length of planet_moon_numbers array.
  uintptr_t planet_moon_numbers_len;
  // Pointer to extra leap-second years. NULL + len=0 means empty.
  const int32_t *extra_leap_seconds;
  // Length of extra_leap_seconds array.
  uintptr_t extra_leap_seconds_len;
  // Precession long-term model. 0 = default.
  int32_t astro_model_prec_longterm;
  // Precession short-term model. 0 = default.
  int32_t astro_model_prec_shortterm;
  // Nutation model. 0 = default.
  int32_t astro_model_nutation;
  // Frame bias model. 0 = default.
  int32_t astro_model_bias;
  // JPL Horizons mode. 0 = default.
  int32_t astro_model_jplhor;
  // JPL Horizons approx mode. 0 = default.
  int32_t astro_model_jplhora;
  // Sidereal time model. 0 = default.
  int32_t astro_model_sidereal_time;
  // Delta T model. 0 = default.
  int32_t astro_model_delta_t;
} SweConfig;

// Per-call sidereal mode override. Nullable in all FFI signatures — NULL means
// "use the handle's configured sidereal mode".
typedef struct SweSidMode {
  // Raw `swe_set_sid_mode` value (bits 0-7 = mode index, upper bits = SiderealBits).
  int32_t sid_mode;
  // Reference epoch for user-defined sidereal (mode index 255).
  double t0;
  // Initial ayanamsa at `t0`.
  double ayan_t0;
} SweSidMode;

// Return the library version as a static NUL-terminated UTF-8 string.
const char *swisseph_version(void);

// Create a new ephemeris handle from a flattened config.
//
// On success, writes the handle to `*out` and returns 0.
// On failure, returns a negative error code and writes a message to `err_buf`.
//
// # Safety
// - `config` must point to a valid `SweConfig` (use `swisseph_config_default` to initialize).
// - `out` must point to a writable `*mut SweEphemeris`.
// - `err_buf` may be NULL; if non-NULL, `err_cap` bytes must be writable.
int32_t swisseph_new(const struct SweConfig *config,
                     SweEphemeris **out,
                     char *err_buf,
                     uintptr_t err_cap);

// Free an ephemeris handle. Null-safe (no-op on NULL).
//
// # Safety
// `handle` must be NULL or a pointer previously returned by `swisseph_new` that has not
// already been freed.
void swisseph_free(SweEphemeris *handle);

// Return the resolved tidal acceleration (arcsec/century^2).
// NAN when unresolved (e.g. Moshier without explicit override).
//
// # Safety
// `handle` must be a valid, non-NULL handle from `swisseph_new`.
double swisseph_get_tid_acc(const SweEphemeris *handle);

// Write the resolved astro model values into `out` (array of 8 i32s).
// Order: prec_longterm, prec_shortterm, nutation, bias, jplhor, jplhora, sidereal_time, delta_t.
//
// # Safety
// - `handle` must be a valid, non-NULL handle from `swisseph_new`.
// - `out` must point to at least 8 writable `i32` slots.
int32_t swisseph_get_astro_models(const SweEphemeris *handle,
                                  int32_t *out,
                                  char *err_buf,
                                  uintptr_t err_cap);

// Compute planetary position at `tjd_ut` (Julian Day, UT1).
//
// # Parameters
// - `handle`: ephemeris handle from `swisseph_new`
// - `tjd_ut`: Julian Day in UT1
// - `ipl`: body number (C `ipl` values, matching `Body` discriminant)
// - `iflag`: calculation flags (C `SEFLG_*` bit values)
// - `geopos`: NULL, or pointer to `[lon, lat, alt]` for a per-call topographic override
// - `sid_mode`: NULL, or pointer to a `SweSidMode` for a per-call sidereal override
// - `xx`: out-param, pointer to 6 `f64` slots receiving [lon, lat, dist, lon_speed, lat_speed, dist_speed]
// - `flags_used`: out-param (may be NULL), pointer to `i32` receiving the flags actually applied
// - `err_buf`, `err_cap`: optional error message buffer
//
// Returns 0 on success, negative error code on failure.
//
// # Safety
// - `handle` must be a valid, non-NULL handle.
// - `xx` must point to at least 6 writable `f64` slots.
// - `geopos`, if non-NULL, must point to 3 readable `f64` values.
int32_t swisseph_calc_ut(const SweEphemeris *handle,
                         double tjd_ut,
                         int32_t ipl,
                         int32_t iflag,
                         const double *geopos,
                         const struct SweSidMode *sid_mode,
                         double *xx,
                         int32_t *flags_used,
                         char *err_buf,
                         uintptr_t err_cap);

// Compute planetary position at `tjd_et` (Julian Day, TT/ET).
//
// # Parameters
// - `handle`: ephemeris handle from `swisseph_new`
// - `tjd_et`: Julian Day in TT/ET
// - `ipl`: body number (C `ipl` values, matching `Body` discriminant)
// - `iflag`: calculation flags (C `SEFLG_*` bit values)
// - `geopos`: NULL, or pointer to `[lon, lat, alt]` for a per-call topographic override
// - `sid_mode`: NULL, or pointer to a `SweSidMode` for a per-call sidereal override
// - `xx`: out-param, pointer to 6 `f64` slots receiving [lon, lat, dist, lon_speed, lat_speed, dist_speed]
// - `flags_used`: out-param (may be NULL), pointer to `i32` receiving the flags actually applied
// - `err_buf`, `err_cap`: optional error message buffer
//
// Returns 0 on success, negative error code on failure.
//
// # Safety
// - `handle` must be a valid, non-NULL handle.
// - `xx` must point to at least 6 writable `f64` slots.
// - `geopos`, if non-NULL, must point to 3 readable `f64` values.
int32_t swisseph_calc(const SweEphemeris *handle,
                      double tjd_et,
                      int32_t ipl,
                      int32_t iflag,
                      const double *geopos,
                      const struct SweSidMode *sid_mode,
                      double *xx,
                      int32_t *flags_used,
                      char *err_buf,
                      uintptr_t err_cap);

// Compute planetocentric position at `tjd_et` (TT).
// Swiss/JPL only — Moshier returns an error.
//
// # Parameters
// - `ipl`: target body
// - `iplctr`: center body (must differ from `ipl`)
// - No `geopos` override (C's `swe_calc_pctr` has no topocentric path)
//
// # Safety
// - `handle` must be a valid, non-NULL handle.
// - `xx` must point to at least 6 writable `f64` slots.
int32_t swisseph_calc_pctr(const SweEphemeris *handle,
                           double tjd_et,
                           int32_t ipl,
                           int32_t iplctr,
                           int32_t iflag,
                           double *xx,
                           int32_t *flags_used,
                           char *err_buf,
                           uintptr_t err_cap);

// Compute fixed-star position at `tjd_et` (TT).
//
// # Parameters
// - `star`: input star name (NUL-terminated UTF-8)
// - `star_out`: buffer receiving the resolved "name,bayer" canonical name (NUL-terminated)
// - `star_out_cap`: capacity of `star_out` in bytes (including NUL)
// - `geopos`: NULL, or `[lon, lat, alt]` for per-call topographic override
// - `sid_mode`: NULL, or per-call sidereal override
// - `xx`: out-param, 6 `f64` slots
// - `flags_used`: out-param (may be NULL)
//
// # Safety
// - `star` must be a valid NUL-terminated UTF-8 string.
// - `star_out` may be NULL; if non-NULL, `star_out_cap` bytes must be writable.
// - `xx` must point to at least 6 writable `f64` slots.
int32_t swisseph_fixstar2(const SweEphemeris *handle,
                          const char *star,
                          char *star_out,
                          uintptr_t star_out_cap,
                          double tjd_et,
                          int32_t iflag,
                          const double *geopos,
                          const struct SweSidMode *sid_mode,
                          double *xx,
                          int32_t *flags_used,
                          char *err_buf,
                          uintptr_t err_cap);

// Compute fixed-star position at `tjd_ut` (UT1).
//
// # Parameters
// - `star`: input star name (NUL-terminated UTF-8)
// - `star_out`: buffer receiving the resolved "name,bayer" canonical name (NUL-terminated);
//   may be NULL if the resolved name is not needed
// - `star_out_cap`: capacity of `star_out` in bytes (including NUL)
// - `geopos`: NULL, or `[lon, lat, alt]` for per-call topographic override
// - `sid_mode`: NULL, or per-call sidereal override
// - `xx`: out-param, pointer to 6 `f64` slots
// - `flags_used`: out-param (may be NULL)
//
// Returns 0 on success, negative error code on failure.
//
// # Safety
// - `star` must be a valid NUL-terminated UTF-8 string.
// - `star_out` may be NULL; if non-NULL, `star_out_cap` bytes must be writable.
// - `xx` must point to at least 6 writable `f64` slots.
int32_t swisseph_fixstar2_ut(const SweEphemeris *handle,
                             const char *star,
                             char *star_out,
                             uintptr_t star_out_cap,
                             double tjd_ut,
                             int32_t iflag,
                             const double *geopos,
                             const struct SweSidMode *sid_mode,
                             double *xx,
                             int32_t *flags_used,
                             char *err_buf,
                             uintptr_t err_cap);

// Look up the magnitude of a fixed star by name.
//
// # Parameters
// - `star`: input star name (NUL-terminated UTF-8)
// - `star_out`: buffer receiving the resolved canonical name (may be NULL)
// - `star_out_cap`: capacity of `star_out`
// - `mag`: out-param receiving the magnitude
//
// # Safety
// - `star` must be a valid NUL-terminated UTF-8 string.
// - `mag` must point to a writable `f64`.
int32_t swisseph_fixstar2_mag(const SweEphemeris *handle,
                              const char *star,
                              char *star_out,
                              uintptr_t star_out_cap,
                              double *mag,
                              char *err_buf,
                              uintptr_t err_cap);

// Ayanamsa at `tjd_et` (TT) with flags. Nutation added unless `NONUT` is set.
//
// # Parameters
// - `sid_mode`: NULL uses the handle's configured sidereal mode; non-NULL overrides per-call
// - `daya`: out-param receiving the ayanamsa in degrees
// - `flags_used`: out-param (may be NULL)
//
// Returns 0 on success, negative error code on failure.
//
// # Safety
// - `handle` must be valid, non-NULL.
// - `daya` must point to a writable `f64`.
int32_t swisseph_get_ayanamsa_ex(const SweEphemeris *handle,
                                 double tjd_et,
                                 int32_t iflag,
                                 const struct SweSidMode *sid_mode,
                                 double *daya,
                                 int32_t *flags_used,
                                 char *err_buf,
                                 uintptr_t err_cap);

// Ayanamsa at `tjd_ut` (UT1) with flags. Nutation added unless `NONUT` is set.
//
// # Parameters
// - `sid_mode`: NULL uses the handle's configured sidereal mode; non-NULL overrides per-call
// - `daya`: out-param receiving the ayanamsa in degrees
// - `flags_used`: out-param (may be NULL)
//
// Returns 0 on success, negative error code on failure.
//
// # Safety
// - `handle` must be valid, non-NULL.
// - `daya` must point to a writable `f64`.
int32_t swisseph_get_ayanamsa_ex_ut(const SweEphemeris *handle,
                                    double tjd_ut,
                                    int32_t iflag,
                                    const struct SweSidMode *sid_mode,
                                    double *daya,
                                    int32_t *flags_used,
                                    char *err_buf,
                                    uintptr_t err_cap);

// Legacy ayanamsa at `tjd_et` (TT), no nutation, returns degrees directly.
// Returns NAN on error (e.g. no sidereal mode configured and no per-call override).
//
// # Safety
// `handle` must be valid, non-NULL.
double swisseph_get_ayanamsa(const SweEphemeris *handle,
                             double tjd_et,
                             const struct SweSidMode *sid_mode);

// Legacy ayanamsa at `tjd_ut` (UT1), no nutation, returns degrees directly.
// Returns NAN on error.
//
// # Safety
// `handle` must be valid, non-NULL.
double swisseph_get_ayanamsa_ut(const SweEphemeris *handle,
                                double tjd_ut,
                                const struct SweSidMode *sid_mode);

// Write the human-readable name for a sidereal mode into `buf`.
// User-defined mode (255) writes an empty string. Unknown mode returns an error.
//
// Handle-free — does not require an ephemeris instance.
//
// # Safety
// - `buf` must point to at least `cap` writable bytes, or be NULL (returns error).
int32_t swisseph_get_ayanamsa_name(int32_t sid_mode_raw,
                                   char *buf,
                                   uintptr_t cap,
                                   char *err_buf,
                                   uintptr_t err_cap);

// Write the display name for a body into `buf` (e.g. "Sun", "Chiron", asteroid name).
//
// # Safety
// - `handle` must be valid, non-NULL.
// - `buf` must point to at least `cap` writable bytes.
int32_t swisseph_get_planet_name(const SweEphemeris *handle,
                                 int32_t ipl,
                                 char *buf,
                                 uintptr_t cap,
                                 char *err_buf,
                                 uintptr_t err_cap);

// Fill a SweConfig with sane defaults (Moshier, no paths, NAN for unset scalars).
//
// # Safety
// `config` must point to a valid, writable `SweConfig`.
void swisseph_config_default(struct SweConfig *config);

// Convert a calendar date + fractional hour (UT) to a Julian Day number.
// `gregflag`: 0 = Julian calendar, 1 = Gregorian calendar.
//
// # Safety
// No pointer arguments.
double swisseph_julday(int32_t year, int32_t month, int32_t day, double hour, int32_t gregflag);

// Convert a Julian Day number to calendar date components.
// `gregflag`: 0 = Julian calendar, 1 = Gregorian calendar.
//
// # Safety
// - `year`, `month`, `day` must point to writable `i32` slots.
// - `hour` must point to a writable `f64`.
void swisseph_revjul(double jd,
                     int32_t gregflag,
                     int32_t *year,
                     int32_t *month,
                     int32_t *day,
                     double *hour);

// Validate and convert a calendar date to a Julian Day.
// Returns 0 on success (writes JD to `*tjd`), or ERR on invalid date.
// `cal`: 'g'/'G' = Gregorian, 'j'/'J' = Julian.
//
// # Safety
// - `tjd` must point to a writable `f64`.
int32_t swisseph_date_conversion(int32_t year,
                                 int32_t month,
                                 int32_t day,
                                 double hour,
                                 char cal,
                                 double *tjd,
                                 char *err_buf,
                                 uintptr_t err_cap);

// Day of the week for a Julian Day: 0 = Monday .. 6 = Sunday.
//
// # Safety
// No pointer arguments.
int32_t swisseph_day_of_week(double jd);

// Shift a UTC date/time by a timezone offset (hours, east positive).
// All time components are both input and output (in-place conversion).
//
// # Safety
// - All pointer arguments must point to writable locations.
void swisseph_utc_time_zone(int32_t iyear,
                            int32_t imonth,
                            int32_t iday,
                            int32_t ihour,
                            int32_t imin,
                            double dsec,
                            double d_timezone,
                            int32_t *oyear,
                            int32_t *omonth,
                            int32_t *oday,
                            int32_t *ohour,
                            int32_t *omin,
                            double *osec);

// Convert UTC to Julian Day (TT and UT1). Writes `dret[0]` = JD(TT), `dret[1]` = JD(UT1).
// `gregflag`: 0 = Julian, 1 = Gregorian.
//
// # Safety
// - `handle` must be a valid, non-NULL handle.
// - `dret` must point to at least 2 writable `f64` slots.
int32_t swisseph_utc_to_jd(const SweEphemeris *handle,
                           int32_t year,
                           int32_t month,
                           int32_t day,
                           int32_t hour,
                           int32_t min,
                           double sec,
                           int32_t gregflag,
                           double *dret,
                           char *err_buf,
                           uintptr_t err_cap);

// Convert Julian Day (TT) to UTC calendar components.
// `gregflag`: 0 = Julian, 1 = Gregorian.
//
// # Safety
// - `handle` must be a valid, non-NULL handle.
// - All out-param pointers must be writable.
void swisseph_jdet_to_utc(const SweEphemeris *handle,
                          double tjd_et,
                          int32_t gregflag,
                          int32_t *year,
                          int32_t *month,
                          int32_t *day,
                          int32_t *hour,
                          int32_t *min,
                          double *sec);

// Convert Julian Day (UT1) to UTC calendar components.
// `gregflag`: 0 = Julian, 1 = Gregorian.
//
// # Safety
// - `handle` must be a valid, non-NULL handle.
// - All out-param pointers must be writable.
void swisseph_jdut1_to_utc(const SweEphemeris *handle,
                           double tjd_ut,
                           int32_t gregflag,
                           int32_t *year,
                           int32_t *month,
                           int32_t *day,
                           int32_t *hour,
                           int32_t *min,
                           double *sec);

// Compute Delta T (TT - UT1) in days for `tjd_ut`.
// Uses the handle's configured ephemeris model.
//
// # Safety
// `handle` must be a valid, non-NULL handle.
double swisseph_deltat(const SweEphemeris *handle, double tjd_ut);

// Compute Delta T (TT - UT1) in days for `tjd_ut`, with iflag-based ephemeris resolution.
// Writes the result to `*deltat`. Returns 0 on success.
//
// The `iflag` EPHMASK bits select which ephemeris backend's tidal acceleration to use.
// Pass `iflag = -1` to force the default tidal acceleration (matching C's sentinel behavior).
//
// # Safety
// - `handle` must be valid, non-NULL.
// - `deltat` must point to a writable `f64`.
int32_t swisseph_deltat_ex(const SweEphemeris *handle,
                           double tjd_ut,
                           int32_t iflag,
                           double *deltat,
                           char *err_buf,
                           uintptr_t err_cap);

// Greenwich Apparent Sidereal Time (hours, 0..24) from `tjd_ut`.
// Uses the handle's configured astro models. Forces TIDAL_DEFAULT internally
// (matching C's `swe_sidtime` behavior).
//
// # Safety
// `handle` must be valid, non-NULL.
double swisseph_sidtime(const SweEphemeris *handle, double tjd_ut);

// Greenwich Apparent Sidereal Time (hours, 0..24) from pre-computed
// true obliquity `eps` (degrees) and nutation in longitude `nut` (degrees).
// Forces TIDAL_DEFAULT internally (matching C's `swe_sidtime0` behavior).
//
// # Safety
// `handle` must be valid, non-NULL.
double swisseph_sidtime0(const SweEphemeris *handle, double tjd_ut, double eps, double nut);

// Equation of time at `tjd_ut` (UT1). Returns `E = LAT − LMT` in **days**.
// Positive means the Sun is ahead of the mean Sun.
//
// # Safety
// - `handle` must be valid, non-NULL.
// - `e` must point to a writable `f64`.
int32_t swisseph_time_equ(const SweEphemeris *handle,
                          double tjd_ut,
                          double *e,
                          char *err_buf,
                          uintptr_t err_cap);

// Convert Local Mean Time to Local Apparent Time.
// `geolon` in degrees (east-positive). `tjd_lmt` and output are Julian Day (UT-scale).
//
// # Safety
// - `handle` must be valid, non-NULL.
// - `tjd_lat` must point to a writable `f64`.
int32_t swisseph_lmt_to_lat(const SweEphemeris *handle,
                            double tjd_lmt,
                            double geolon,
                            double *tjd_lat,
                            char *err_buf,
                            uintptr_t err_cap);

// Convert Local Apparent Time to Local Mean Time.
// `geolon` in degrees (east-positive). `tjd_lat` and output are Julian Day (UT-scale).
//
// # Safety
// - `handle` must be valid, non-NULL.
// - `tjd_lmt` must point to a writable `f64`.
int32_t swisseph_lat_to_lmt(const SweEphemeris *handle,
                            double tjd_lat,
                            double geolon,
                            double *tjd_lmt,
                            char *err_buf,
                            uintptr_t err_cap);

// Round centiseconds to the nearest arcsecond with a 30°-boundary guard.
//
// # Safety
// No pointer arguments.
int32_t swisseph_csroundsec(int32_t x);

// Format time-of-day centiseconds as `"HH:MM:SS"` into `buf`.
// `sep` is the separator character (e.g. ':').
// `suppress_zero`: if true, omits seconds when they are zero.
//
// # Safety
// - `buf` must point to at least `cap` writable bytes.
void swisseph_cs2timestr(int32_t t, char sep, bool suppress_zero, char *buf, uintptr_t cap);

// Format arc centiseconds as a longitude/latitude string with direction letters.
// `pchar` for positive, `mchar` for negative.
//
// # Safety
// - `buf` must point to at least `cap` writable bytes.
void swisseph_cs2lonlatstr(int32_t t, char pchar, char mchar, char *buf, uintptr_t cap);

// Format arc centiseconds as degrees-within-sign (`" D°MM'SS"`).
// Truncates (no rounding) and wraps into [0, 30°).
//
// # Safety
// - `buf` must point to at least `cap` writable bytes.
void swisseph_cs2degstr(int32_t t, char *buf, uintptr_t cap);

// Split a decimal degree value into components. Mirrors C's `swe_split_deg`.
//
// # Parameters
// - `ddeg`: decimal degrees to split
// - `roundflag`: combination of SE_SPLIT_DEG_* flags
// - `deg`, `min`, `sec`: out-params for integer components
// - `secfr`: out-param for fractional seconds
// - `sign`: out-param for sign (zodiacal sign index, or ±1)
//
// # Safety
// All out-param pointers must be writable.
void swisseph_split_deg(double ddeg,
                        int32_t roundflag,
                        int32_t *deg,
                        int32_t *min,
                        int32_t *sec,
                        double *secfr,
                        int32_t *sign);

// Rise/set/meridian-transit search at `tjd_ut` (UT1).
//
// Returns 0 on success, **-2** for circumpolar body (no error message — this is
// a status, not an error, matching C convention), or a negative error code with
// a message in `err_buf`.
//
// # Parameters
// - `ipl`: body number
// - `starname`: fixed star name (NUL-terminated), or NULL for a planet
// - `epheflag`: calculation flags (SEFLG_MOSEPH etc.)
// - `rsmi`: rise/set event selector (SE_CALC_RISE=1, SE_CALC_SET=2, etc.)
// - `geopos`: [lon, lat, height], 3 `f64` values
// - `atpress`: atmospheric pressure (hPa)
// - `attemp`: atmospheric temperature (°C)
// - `tret`: out, pointer to 1 `f64` receiving the event time (UT)
//
// # Safety
// - `handle` must be valid, non-NULL.
// - `geopos` must point to 3 readable `f64` values.
// - `tret` must point to a writable `f64`.
int32_t swisseph_rise_trans(const SweEphemeris *handle,
                            double tjd_ut,
                            int32_t ipl,
                            const char *starname,
                            int32_t epheflag,
                            int32_t rsmi,
                            const double *geopos,
                            double atpress,
                            double attemp,
                            double *tret,
                            char *err_buf,
                            uintptr_t err_cap);

// Rise/set/meridian-transit search with custom horizon height at `tjd_ut` (UT1).
//
// Same return convention as [`swisseph_rise_trans`]: 0 = success, -2 = circumpolar,
// negative = error.
//
// # Parameters
// - `horhgt`: horizon height in degrees (-100 = auto-dip from `geopos[2]`)
//
// # Safety
// - `handle` must be valid, non-NULL.
// - `geopos` must point to 3 readable `f64` values.
// - `tret` must point to a writable `f64`.
int32_t swisseph_rise_trans_true_hor(const SweEphemeris *handle,
                                     double tjd_ut,
                                     int32_t ipl,
                                     const char *starname,
                                     int32_t epheflag,
                                     int32_t rsmi,
                                     const double *geopos,
                                     double atpress,
                                     double attemp,
                                     double horhgt,
                                     double *tret,
                                     char *err_buf,
                                     uintptr_t err_cap);

// Geographic position of greatest solar eclipse at `tjd_ut` (UT1).
//
// On success returns **positive** EclipseFlags bits (CENTRAL/NONCENTRAL/TOTAL/ANNULAR/PARTIAL);
// 0 (empty flags) means no eclipse at this instant. Negative = error.
//
// `geopos[10]` out: [0]=lon, [1]=lat, [2..8]=shadow-cone geometry (core_diameter_km,
// penumbra_diameter_km, shadow_axis_distance_km, umbra_fundamental_km, penumbra_fundamental_km,
// cos_umbra_half, cos_penumbra_half), [9]=0.
//
// `attr[20]` out: zeroed — local circumstances require [`swisseph_sol_eclipse_how`].
//
// # Safety
// - `handle`, `geopos`, `attr` must be valid, non-NULL.
int32_t swisseph_sol_eclipse_where(const SweEphemeris *handle,
                                   double tjd_ut,
                                   int32_t ifl,
                                   double *geopos,
                                   double *attr,
                                   char *err_buf,
                                   uintptr_t err_cap);

// Local circumstances of a solar eclipse at observer `geopos` at `tjd_ut` (UT1).
//
// On success returns **positive** EclipseFlags bits; 0 = no eclipse visible.
// Negative = error.
//
// `attr[20]` out: [0]=magnitude, [1]=diameter_ratio, [2]=obscuration,
// [3]=core_diameter_km, [4]=azimuth, [5]=true_altitude, [6]=apparent_altitude,
// [7]=elongation, [8]=nasa_magnitude, [9]=saros_series, [10]=saros_member, [11..19]=0.
//
// # Safety
// - `handle` must be valid, non-NULL.
// - `geopos` must point to 3 readable `f64` values [lon, lat, height].
// - `attr` must point to at least 20 writable `f64` slots.
int32_t swisseph_sol_eclipse_how(const SweEphemeris *handle,
                                 double tjd_ut,
                                 int32_t ifl,
                                 const double *geopos,
                                 double *attr,
                                 char *err_buf,
                                 uintptr_t err_cap);

// Global solar eclipse search from `tjd_start` (UT1).
//
// On success returns **positive** EclipseFlags bits. Negative = error.
//
// `tret[10]` out: [0]=time_maximum, [1]=time_ra_conjunction, [2]=time_begin, [3]=time_end,
// [4]=time_totality_begin, [5]=time_totality_end, [6]=time_centerline_begin,
// [7]=time_centerline_end, [8..9]=0.
//
// # Safety
// - `handle` must be valid, non-NULL.
// - `tret` must point to at least 10 writable `f64` slots.
int32_t swisseph_sol_eclipse_when_glob(const SweEphemeris *handle,
                                       double tjd_start,
                                       int32_t ifl,
                                       int32_t ifltype,
                                       int32_t backward,
                                       double *tret,
                                       char *err_buf,
                                       uintptr_t err_cap);

// Local solar eclipse search from `tjd_start` (UT1), visible from `geopos`.
//
// On success returns **positive** EclipseFlags bits. Negative = error.
//
// `tret[10]` out: [0]=time_maximum, [1]=time_first_contact, [2]=time_second_contact,
// [3]=time_third_contact, [4]=time_fourth_contact, [5]=time_sunrise, [6]=time_sunset,
// [7..9]=0. **Different slot semantics from sol_eclipse_when_glob.**
//
// `attr[20]` out: local circumstances at maximum (same layout as sol_eclipse_how).
//
// # Safety
// - `handle` must be valid, non-NULL.
// - `geopos` must point to 3 readable `f64` values.
// - `tret` must point to at least 10 writable `f64` slots.
// - `attr` must point to at least 20 writable `f64` slots.
int32_t swisseph_sol_eclipse_when_loc(const SweEphemeris *handle,
                                      double tjd_start,
                                      int32_t ifl,
                                      const double *geopos,
                                      int32_t backward,
                                      double *tret,
                                      double *attr,
                                      char *err_buf,
                                      uintptr_t err_cap);

// Local circumstances of a lunar eclipse at observer `geopos` at `tjd_ut` (UT1).
//
// On success returns **positive** EclipseFlags bits; 0 = no eclipse visible.
// Negative = error.
//
// `attr[20]` out: [0]=umbral_magnitude, [1]=penumbral_magnitude, [2]=0, [3]=0,
// [4]=azimuth, [5]=true_altitude, [6]=apparent_altitude, [7]=distance_from_opposition,
// [8]=umbral_magnitude (dup), [9]=saros_series, [10]=saros_member, [11..19]=0.
//
// # Safety
// - `handle` must be valid, non-NULL.
// - `geopos` must point to 3 readable `f64` values.
// - `attr` must point to at least 20 writable `f64` slots.
int32_t swisseph_lun_eclipse_how(const SweEphemeris *handle,
                                 double tjd_ut,
                                 int32_t ifl,
                                 const double *geopos,
                                 double *attr,
                                 char *err_buf,
                                 uintptr_t err_cap);

// Global lunar eclipse search from `tjd_start` (UT1).
//
// On success returns **positive** EclipseFlags bits. Negative = error.
//
// `tret[10]` out: [0]=time_maximum, [1]=0 (unused), [2]=time_partial_begin,
// [3]=time_partial_end, [4]=time_totality_begin, [5]=time_totality_end,
// [6]=time_penumbral_begin, [7]=time_penumbral_end, [8..9]=0.
//
// # Safety
// - `handle` must be valid, non-NULL.
// - `tret` must point to at least 10 writable `f64` slots.
int32_t swisseph_lun_eclipse_when(const SweEphemeris *handle,
                                  double tjd_start,
                                  int32_t ifl,
                                  int32_t ifltype,
                                  int32_t backward,
                                  double *tret,
                                  char *err_buf,
                                  uintptr_t err_cap);

// Local lunar eclipse search from `tjd_start` (UT1), visible from `geopos`.
//
// On success returns **positive** EclipseFlags bits. Negative = error.
//
// `tret[10]` out: [0]=time_maximum, [1]=0 (unused), [2]=time_partial_begin,
// [3]=time_partial_end, [4]=time_totality_begin, [5]=time_totality_end,
// [6]=time_penumbral_begin, [7]=time_penumbral_end, [8]=time_moonrise,
// [9]=time_moonset.
//
// `attr[20]` out: lunar eclipse circumstances (same layout as lun_eclipse_how).
//
// # Safety
// - `handle` must be valid, non-NULL.
// - `geopos` must point to 3 readable `f64` values.
// - `tret` must point to at least 10 writable `f64` slots.
// - `attr` must point to at least 20 writable `f64` slots.
int32_t swisseph_lun_eclipse_when_loc(const SweEphemeris *handle,
                                      double tjd_start,
                                      int32_t ifl,
                                      const double *geopos,
                                      int32_t backward,
                                      double *tret,
                                      double *attr,
                                      char *err_buf,
                                      uintptr_t err_cap);

// Geographic position of maximal lunar occultation at `tjd_ut` (UT1).
//
// On success returns **positive** EclipseFlags bits. Negative = error.
//
// `geopos[10]` out: same layout as [`swisseph_sol_eclipse_where`].
// `attr[20]` out: zeroed — local circumstances require the `_how`-level API.
//
// # Safety
// - `handle` must be valid, non-NULL.
// - `geopos`, `attr` must point to at least 10/20 writable `f64` slots.
int32_t swisseph_lun_occult_where(const SweEphemeris *handle,
                                  double tjd_ut,
                                  int32_t ipl,
                                  const char *starname,
                                  int32_t ifl,
                                  double *geopos,
                                  double *attr,
                                  char *err_buf,
                                  uintptr_t err_cap);

// Global occultation search from `tjd_start` (UT1).
//
// On success returns **positive** EclipseFlags bits. Negative = error.
//
// `tret[10]` out: same slot layout as [`swisseph_sol_eclipse_when_glob`], but `tret[1]`
// is the occulted body's transit instant (not specifically the Sun's).
//
// # Safety
// - `handle` must be valid, non-NULL.
// - `tret` must point to at least 10 writable `f64` slots.
int32_t swisseph_lun_occult_when_glob(const SweEphemeris *handle,
                                      double tjd_start,
                                      int32_t ipl,
                                      const char *starname,
                                      int32_t ifl,
                                      int32_t ifltype,
                                      int32_t backward,
                                      double *tret,
                                      char *err_buf,
                                      uintptr_t err_cap);

// Local occultation search from `tjd_start` (UT1), visible from `geopos`.
//
// On success returns **positive** EclipseFlags bits. Negative = error.
//
// `tret[10]` out: [0]=time_maximum, [1]=time_first_contact, [2]=time_second_contact,
// [3]=time_third_contact, [4]=time_fourth_contact, [5]=time_rise, [6]=time_set,
// [7..9]=0. Same slot semantics as [`swisseph_sol_eclipse_when_loc`]; for a fixed star,
// contacts 1/4 alias contacts 2/3.
//
// `attr[20]` out: local circumstances at maximum (same layout as sol_eclipse_how).
//
// # Safety
// - `handle` must be valid, non-NULL.
// - `geopos` must point to 3 readable `f64` values.
// - `tret` must point to at least 10 writable `f64` slots.
// - `attr` must point to at least 20 writable `f64` slots.
int32_t swisseph_lun_occult_when_loc(const SweEphemeris *handle,
                                     double tjd_start,
                                     int32_t ipl,
                                     const char *starname,
                                     int32_t ifl,
                                     const double *geopos,
                                     int32_t backward,
                                     double *tret,
                                     double *attr,
                                     char *err_buf,
                                     uintptr_t err_cap);

// Compute tropical house cusps and angular points at `tjd_ut` (UT1).
//
// # Parameters
// - `handle`: ephemeris handle from `swisseph_new`
// - `tjd_ut`: Julian Day in UT1
// - `geolat`: geographic latitude (north positive), degrees
// - `geolon`: geographic longitude (east positive), degrees
// - `hsys`: house system as ASCII char code (e.g. `'P'` for Placidus)
// - `cusps`: out, must point to at least 13 writable `f64` slots (37 for `'G'` Gauquelin)
// - `ascmc`: out, must point to at least 10 writable `f64` slots.
//   Layout: [0]=Asc, [1]=MC, [2]=ARMC, [3]=Vertex, [4]=equatorial Asc,
//   [5]=co-Asc (Koch), [6]=co-Asc (Munkasey), [7]=polar Asc, [8]=0, [9]=0.
//
// # Safety
// - `handle` must be a valid, non-NULL handle.
// - `cusps` must point to at least 13 (or 37 for Gauquelin) writable `f64` slots.
// - `ascmc` must point to at least 10 writable `f64` slots.
int32_t swisseph_houses(const SweEphemeris *handle,
                        double tjd_ut,
                        double geolat,
                        double geolon,
                        int32_t hsys,
                        double *cusps,
                        double *ascmc,
                        char *err_buf,
                        uintptr_t err_cap);

// Compute house cusps and angular points at `tjd_ut` (UT1) with flags.
//
// Sidereal mode (when `SEFLG_SIDEREAL` is set in `iflag`) uses the mode
// configured on the handle at construction time.
//
// # Parameters
// - `iflag`: calculation flags (e.g. `SEFLG_SIDEREAL`)
// - `cusps`: out, at least 13 `f64` slots (37 for Gauquelin)
// - `ascmc`: out, at least 10 `f64` slots
//
// ascmc layout: [0]=Asc, [1]=MC, [2]=ARMC, [3]=Vertex, [4]=equatorial Asc,
// [5]=co-Asc (Koch), [6]=co-Asc (Munkasey), [7]=polar Asc, [8..9]=0.
//
// # Safety
// - `handle` must be a valid, non-NULL handle.
// - `cusps` must point to at least 13 (or 37 for Gauquelin) writable `f64` slots.
// - `ascmc` must point to at least 10 writable `f64` slots.
int32_t swisseph_houses_ex(const SweEphemeris *handle,
                           double tjd_ut,
                           int32_t iflag,
                           double geolat,
                           double geolon,
                           int32_t hsys,
                           double *cusps,
                           double *ascmc,
                           char *err_buf,
                           uintptr_t err_cap);

// Compute house cusps, angular points, and their speeds at `tjd_ut` (UT1).
//
// Sidereal mode (when `SEFLG_SIDEREAL` is set in `iflag`) uses the mode
// configured on the handle at construction time.
//
// # Parameters
// - `cusp_speed`: out, nullable — cusp speeds (degrees/day), same sizing as `cusps`
// - `ascmc_speed`: out, nullable — angular-point speeds (10 slots, same layout as `ascmc`)
//
// Cusps must be sized 13 for all systems except Gauquelin ('G') which needs 37.
//
// # Safety
// - `handle` must be a valid, non-NULL handle.
// - `cusps`, `ascmc` must be valid and properly sized.
// - `cusp_speed`, `ascmc_speed` may be NULL (speeds omitted).
int32_t swisseph_houses_ex2(const SweEphemeris *handle,
                            double tjd_ut,
                            int32_t iflag,
                            double geolat,
                            double geolon,
                            int32_t hsys,
                            double *cusps,
                            double *ascmc,
                            double *cusp_speed,
                            double *ascmc_speed,
                            char *err_buf,
                            uintptr_t err_cap);

// Compute house cusps from ARMC, obliquity, and geographic latitude directly.
//
// Handle-free function — does not need an Ephemeris instance.
//
// ascmc layout: [0]=Asc, [1]=MC, [2]=ARMC, [3]=Vertex, [4]=equatorial Asc,
// [5]=co-Asc (Koch), [6]=co-Asc (Munkasey), [7]=polar Asc, [8]=0, [9]=0.
//
// # Safety
// - `cusps` must point to at least 13 (or 37 for Gauquelin) writable `f64` slots.
// - `ascmc` must point to at least 10 writable `f64` slots.
int32_t swisseph_houses_armc(double armc,
                             double geolat,
                             double eps,
                             int32_t hsys,
                             double *cusps,
                             double *ascmc,
                             char *err_buf,
                             uintptr_t err_cap);

// Compute house cusps and speeds from ARMC, obliquity, and geographic latitude.
//
// Handle-free. `sundec` is required for Sunshine house systems (`'I'`/`'i'`);
// pass NULL for all others.
//
// ascmc/ascmc_speed layout: [0]=Asc, [1]=MC, [2]=ARMC, [3]=Vertex,
// [4]=equatorial Asc, [5]=co-Asc (Koch), [6]=co-Asc (Munkasey),
// [7]=polar Asc, [8]=0, [9]=0.
//
// # Safety
// - `cusps`, `ascmc` must be valid and properly sized.
// - `cusp_speed`, `ascmc_speed` may be NULL.
// - `sundec` may be NULL (required for Sunshine systems).
int32_t swisseph_houses_armc_ex2(double armc,
                                 double geolat,
                                 double eps,
                                 int32_t hsys,
                                 const double *sundec,
                                 double *cusps,
                                 double *ascmc,
                                 double *cusp_speed,
                                 double *ascmc_speed,
                                 char *err_buf,
                                 uintptr_t err_cap);

// Compute the house position of a planet (continuous 1.0..13.0 for 12-house
// systems, 1.0..37.0 for Gauquelin).
//
// # Parameters
// - `armc`: sidereal time as ARMC (degrees)
// - `geolat`: geographic latitude (degrees)
// - `eps`: obliquity of ecliptic (degrees)
// - `hsys`: house system (ASCII char)
// - `xpin`: ecliptic longitude and latitude of the planet, 2 `f64` values
// - `sundec`: Sun declination, required for Sunshine (`'I'`/`'i'`); NULL otherwise
// - `hpos`: out, house position (1.0..13.0 or 1.0..37.0)
//
// # Safety
// - `xpin` must point to 2 readable `f64` values.
// - `hpos` must point to a writable `f64`.
// - `sundec` may be NULL.
int32_t swisseph_house_pos(double armc,
                           double geolat,
                           double eps,
                           int32_t hsys,
                           const double *xpin,
                           const double *sundec,
                           double *hpos,
                           char *err_buf,
                           uintptr_t err_cap);

// Get the human-readable name of a house system.
//
// Handle-free. Writes the name to `buf` (NUL-terminated, truncated if needed).
//
// # Safety
// - `buf` must point to at least `cap` writable bytes.
int32_t swisseph_house_name(int32_t hsys,
                            char *buf,
                            uintptr_t cap,
                            char *err_buf,
                            uintptr_t err_cap);

// Compute a Gauquelin sector position at `tjd_ut` (UT1).
//
// # Parameters
// - `ipl`: planet body ID
// - `starname`: fixed star name (NUL-terminated), or NULL for a planet
// - `iflag`: calculation flags
// - `imeth`: method (0/1 = geometric, 2–5 = rise/set-based)
// - `geopos`: geographic position [lon, lat, height], 3 `f64` values
// - `atpress`: atmospheric pressure (hPa), for rise/set methods
// - `attemp`: atmospheric temperature (°C), for rise/set methods
// - `dgsect`: out, Gauquelin sector (1.0..36.x)
//
// # Safety
// - `handle` must be a valid, non-NULL handle.
// - `geopos` must point to 3 readable `f64` values.
// - `dgsect` must point to a writable `f64`.
// - `starname` may be NULL.
int32_t swisseph_gauquelin_sector(const SweEphemeris *handle,
                                  double tjd_ut,
                                  int32_t ipl,
                                  const char *starname,
                                  int32_t iflag,
                                  int32_t imeth,
                                  const double *geopos,
                                  double atpress,
                                  double attemp,
                                  double *dgsect,
                                  char *err_buf,
                                  uintptr_t err_cap);

// Convert ecliptic/equatorial coordinates to horizontal (azimuth + altitude).
//
// # Parameters
// - `calc_flag`: `SE_ECL2HOR` (0) or `SE_EQU2HOR` (1)
// - `geopos`: [longitude, latitude, height], 3 `f64` values
// - `atpress`: atmospheric pressure (hPa) — 0 auto-estimates from `geopos[2]` altitude
// - `attemp`: atmospheric temperature (°C)
// - `xin`: input [longitude/RA, latitude/declination], 2 `f64` values
// - `xaz`: out [azimuth, true altitude, apparent altitude], 3 `f64` values
//
// # Safety
// - `handle` must be valid, non-NULL.
// - `geopos` must point to 3 readable `f64` values.
// - `xin` must point to 2 readable `f64` values (only [0] and [1] used).
// - `xaz` must point to 3 writable `f64` values.
void swisseph_azalt(const SweEphemeris *handle,
                    double tjd_ut,
                    int32_t calc_flag,
                    const double *geopos,
                    double atpress,
                    double attemp,
                    const double *xin,
                    double *xaz);

// Convert horizontal (azimuth + altitude) back to ecliptic/equatorial.
//
// # Parameters
// - `calc_flag`: `SE_HOR2ECL` (0) or `SE_HOR2EQU` (1)
// - `geopos`: [longitude, latitude, height], 3 `f64` values
// - `xin`: [azimuth (from south, clockwise), true altitude], 2 `f64` values
// - `xout`: out [lon/RA, lat/dec], 2 `f64` values
//
// # Safety
// - `handle` must be valid, non-NULL.
// - `geopos` must point to 3 readable `f64` values.
// - `xin` must point to 2 readable `f64` values.
// - `xout` must point to 2 writable `f64` values.
void swisseph_azalt_rev(const SweEphemeris *handle,
                        double tjd_ut,
                        int32_t calc_flag,
                        const double *geopos,
                        const double *xin,
                        double *xout);

// Simple atmospheric refraction (sea-level, no dip).
//
// Handle-free.
//
// # Parameters
// - `inalt`: input altitude (degrees)
// - `atpress`: atmospheric pressure (hPa)
// - `attemp`: atmospheric temperature (°C)
// - `calc_flag`: `SE_TRUE_TO_APP` (0) or `SE_APP_TO_TRUE` (1)
//
// Returns the refracted/de-refracted altitude (degrees).
double swisseph_refrac(double inalt, double atpress, double attemp, int32_t calc_flag);

// Extended atmospheric refraction with horizon dip for an elevated observer.
//
// Handle-free.
//
// # Parameters
// - `inalt`: input altitude (degrees)
// - `geoalt`: observer height above sea level (meters)
// - `atpress`: atmospheric pressure (hPa)
// - `attemp`: atmospheric temperature (°C)
// - `lapse_rate`: temperature lapse rate (K/m), typically 0.0065
// - `calc_flag`: `SE_TRUE_TO_APP` (0) or `SE_APP_TO_TRUE` (1)
// - `dret`: out, 4 `f64` values: [true alt, apparent alt, refraction, dip]
//
// Returns the refracted/de-refracted altitude.
//
// # Safety
// - `dret` must point to at least 4 writable `f64` slots.
double swisseph_refrac_extended(double inalt,
                                double geoalt,
                                double atpress,
                                double attemp,
                                double lapse_rate,
                                int32_t calc_flag,
                                double *dret);

// Planetary phenomena (phase angle, elongation, magnitude, etc.) at `tjd_et` (TT).
//
// # Parameters
// - `ipl`: body number
// - `iflag`: calculation flags
// - `geopos`: NULL, or pointer to `[lon, lat, alt]` for a per-call topographic override
//   (needed when `SEFLG_TOPOCTR` is set for Moon horizontal parallax)
// - `sid_mode`: NULL, or pointer to a `SweSidMode` for a per-call sidereal override
// - `attr`: out-param, pointer to 20 `f64` slots. `attr[0]`=phase_angle, `[1]`=phase,
//   `[2]`=elongation, `[3]`=apparent_diameter, `[4]`=apparent_magnitude,
//   `[5]`=horizontal_parallax, `[6..19]`=0.
// - `flags_used`: out-param (may be NULL), flags actually applied
//
// Returns 0 on success, negative error code on failure.
//
// # Safety
// - `handle` must be valid, non-NULL.
// - `geopos`, if non-NULL, must point to 3 readable `f64` values.
// - `attr` must point to at least 20 writable `f64` slots.
int32_t swisseph_pheno(const SweEphemeris *handle,
                       double tjd_et,
                       int32_t ipl,
                       int32_t iflag,
                       const double *geopos,
                       const struct SweSidMode *sid_mode,
                       double *attr,
                       int32_t *flags_used,
                       char *err_buf,
                       uintptr_t err_cap);

// Planetary phenomena at `tjd_ut` (UT1). See [`swisseph_pheno`] for details.
//
// # Safety
// - `handle` must be valid, non-NULL.
// - `geopos`, if non-NULL, must point to 3 readable `f64` values.
// - `attr` must point to at least 20 writable `f64` slots.
int32_t swisseph_pheno_ut(const SweEphemeris *handle,
                          double tjd_ut,
                          int32_t ipl,
                          int32_t iflag,
                          const double *geopos,
                          const struct SweSidMode *sid_mode,
                          double *attr,
                          int32_t *flags_used,
                          char *err_buf,
                          uintptr_t err_cap);

// Nodes and apsides at `tjd_et` (TT).
//
// # Parameters
// - `ipl`: body number
// - `iflag`: calculation flags
// - `method`: `NodApsMethod` bits (1=MEAN, 2=OSCU, 4=OSCU_BAR, 256=FOPOINT)
// - `xnasc`, `xndsc`, `xperi`, `xaphe`: out-params, each pointer to 6 `f64` slots
//   receiving ascending node, descending node, perihelion, aphelion respectively
//
// Returns 0 on success, negative error code on failure.
//
// # Safety
// - `handle` must be valid, non-NULL.
// - All four output pointers must point to at least 6 writable `f64` slots.
int32_t swisseph_nod_aps(const SweEphemeris *handle,
                         double tjd_et,
                         int32_t ipl,
                         int32_t iflag,
                         int32_t method,
                         double *xnasc,
                         double *xndsc,
                         double *xperi,
                         double *xaphe,
                         char *err_buf,
                         uintptr_t err_cap);

// Nodes and apsides at `tjd_ut` (UT1). See [`swisseph_nod_aps`] for details.
//
// # Safety
// - `handle` must be valid, non-NULL.
// - All four output pointers must point to at least 6 writable `f64` slots.
int32_t swisseph_nod_aps_ut(const SweEphemeris *handle,
                            double tjd_ut,
                            int32_t ipl,
                            int32_t iflag,
                            int32_t method,
                            double *xnasc,
                            double *xndsc,
                            double *xperi,
                            double *xaphe,
                            char *err_buf,
                            uintptr_t err_cap);

// Osculating orbital elements at `tjd_et` (TT).
//
// # Parameters
// - `ipl`: body number
// - `iflag`: calculation flags
// - `dret`: out-param, pointer to 50 `f64` slots. Slots `[0..16]` receive the 17 named
//   orbital element fields (see `OrbitalElements::as_array` for slot meanings):
//   `[0]`=semi_major_axis, `[1]`=eccentricity, `[2]`=inclination,
//   `[3]`=ascending_node (Ω), `[4]`=arg_perihelion (ω), `[5]`=perihelion_lon (ϖ),
//   `[6]`=mean_anomaly, `[7]`=true_anomaly, `[8]`=eccentric_anomaly,
//   `[9]`=mean_longitude, `[10]`=sidereal_period, `[11]`=mean_daily_motion,
//   `[12]`=tropical_period, `[13]`=synodic_period, `[14]`=perihelion_passage (JD TT),
//   `[15]`=perihelion_distance, `[16]`=aphelion_distance.
//   Slots `[17..49]` are zeroed.
//
// Returns 0 on success, negative error code on failure.
//
// # Safety
// - `handle` must be valid, non-NULL.
// - `dret` must point to at least 50 writable `f64` slots.
int32_t swisseph_get_orbital_elements(const SweEphemeris *handle,
                                      double tjd_et,
                                      int32_t ipl,
                                      int32_t iflag,
                                      double *dret,
                                      char *err_buf,
                                      uintptr_t err_cap);

// Maximum, minimum, and current true distance for a body at `tjd_et` (TT).
//
// # Parameters
// - `dmax`, `dmin`, `dtrue`: out-params, pointers to writable `f64` values
//
// Returns 0 on success, negative error code on failure.
//
// # Safety
// - `handle` must be valid, non-NULL.
// - `dmax`, `dmin`, `dtrue` must each point to a writable `f64`.
int32_t swisseph_orbit_max_min_true_distance(const SweEphemeris *handle,
                                             double tjd_et,
                                             int32_t ipl,
                                             int32_t iflag,
                                             double *dmax,
                                             double *dmin,
                                             double *dtrue,
                                             char *err_buf,
                                             uintptr_t err_cap);

// Next Julian Day (TT) at which the Sun's ecliptic longitude equals `x2cross` (degrees).
//
// **Return convention differs from C:** returns `i32` status (0=OK, negative=error),
// crossing JD written to `*jx`. C returns the JD directly with error signaled by
// `jd < tjd` — this FFI uses the uniform out-param convention instead.
//
// # Safety
// - `handle` must be valid, non-NULL.
// - `jx` must point to a writable `f64`.
int32_t swisseph_solcross(const SweEphemeris *handle,
                          double x2cross,
                          double tjd_et,
                          int32_t iflag,
                          double *jx,
                          char *err_buf,
                          uintptr_t err_cap);

// UT-based [`swisseph_solcross`]. See that function for the return convention note.
//
// # Safety
// - `handle` must be valid, non-NULL.
// - `jx` must point to a writable `f64`.
int32_t swisseph_solcross_ut(const SweEphemeris *handle,
                             double x2cross,
                             double tjd_ut,
                             int32_t iflag,
                             double *jx,
                             char *err_buf,
                             uintptr_t err_cap);

// Next Julian Day (TT) at which the Moon's ecliptic longitude equals `x2cross` (degrees).
//
// **Return convention differs from C** — see [`swisseph_solcross`].
//
// # Safety
// - `handle` must be valid, non-NULL.
// - `jx` must point to a writable `f64`.
int32_t swisseph_mooncross(const SweEphemeris *handle,
                           double x2cross,
                           double tjd_et,
                           int32_t iflag,
                           double *jx,
                           char *err_buf,
                           uintptr_t err_cap);

// UT-based [`swisseph_mooncross`].
//
// # Safety
// - `handle` must be valid, non-NULL.
// - `jx` must point to a writable `f64`.
int32_t swisseph_mooncross_ut(const SweEphemeris *handle,
                              double x2cross,
                              double tjd_ut,
                              int32_t iflag,
                              double *jx,
                              char *err_buf,
                              uintptr_t err_cap);

// Next Julian Day (TT) at which the Moon crosses its node (ecliptic latitude = 0).
//
// **Return convention differs from C** — see [`swisseph_solcross`].
//
// # Parameters
// - `jx`: out, crossing JD
// - `xlon`: out, Moon's ecliptic longitude at the crossing (degrees)
// - `xlat`: out, Moon's ecliptic latitude at the crossing (degrees, near zero)
//
// # Safety
// - `handle` must be valid, non-NULL.
// - `jx`, `xlon`, `xlat` must each point to a writable `f64`.
int32_t swisseph_mooncross_node(const SweEphemeris *handle,
                                double tjd_et,
                                int32_t iflag,
                                double *xlon,
                                double *xlat,
                                double *jx,
                                char *err_buf,
                                uintptr_t err_cap);

// UT-based [`swisseph_mooncross_node`].
//
// # Safety
// - `handle` must be valid, non-NULL.
// - `jx`, `xlon`, `xlat` must each point to a writable `f64`.
int32_t swisseph_mooncross_node_ut(const SweEphemeris *handle,
                                   double tjd_ut,
                                   int32_t iflag,
                                   double *xlon,
                                   double *xlat,
                                   double *jx,
                                   char *err_buf,
                                   uintptr_t err_cap);

// Next Julian Day (TT) at which `ipl`'s heliocentric longitude equals `x2cross` (degrees).
// `dir >= 0` searches forward, `dir < 0` searches backward.
//
// **Return convention differs from C** — see [`swisseph_solcross`].
//
// # Safety
// - `handle` must be valid, non-NULL.
// - `jx` must point to a writable `f64`.
int32_t swisseph_helio_cross(const SweEphemeris *handle,
                             int32_t ipl,
                             double x2cross,
                             double tjd_et,
                             int32_t iflag,
                             int32_t dir,
                             double *jx,
                             char *err_buf,
                             uintptr_t err_cap);

// UT-based [`swisseph_helio_cross`].
//
// # Safety
// - `handle` must be valid, non-NULL.
// - `jx` must point to a writable `f64`.
int32_t swisseph_helio_cross_ut(const SweEphemeris *handle,
                                int32_t ipl,
                                double x2cross,
                                double tjd_ut,
                                int32_t iflag,
                                int32_t dir,
                                double *jx,
                                char *err_buf,
                                uintptr_t err_cap);

// Normalize degrees to [0, 360). Port of `swe_degnorm`.
double swisseph_degnorm(double x);

// Normalize radians to [0, 2π). Port of `swe_radnorm`.
double swisseph_radnorm(double x);

// Difference `p1 - p2` normalized to [0, 360). Port of `swe_difdegn`.
double swisseph_difdegn(double p1, double p2);

// Difference `p1 - p2` normalized to [-180, 180). Port of `swe_difdeg2n`.
double swisseph_difdeg2n(double p1, double p2);

// Midpoint of two degree values on the 360° circle. Port of `swe_deg_midp`.
double swisseph_deg_midp(double x1, double x0);

// Midpoint of two radian values on the 2π circle. Port of `swe_rad_midp`.
double swisseph_rad_midp(double x1, double x0);

// Coordinate transformation (ecliptic ↔ equatorial).
// `xpo[3]` in, `xpn[3]` out. `eps` in degrees.
//
// # Safety
// - `xpo` must point to 3 readable `f64` values.
// - `xpn` must point to 3 writable `f64` values.
void swisseph_cotrans(const double *xpo, double *xpn, double eps);

// Coordinate transformation with speed (ecliptic ↔ equatorial).
// `xpo[6]` in (pos + speed), `xpn[6]` out. `eps` in degrees.
//
// # Safety
// - `xpo` must point to 6 readable `f64` values.
// - `xpn` must point to 6 writable `f64` values.
void swisseph_cotrans_sp(const double *xpo, double *xpn, double eps);

#endif  /* SWISSEPH_H */
