#!/usr/bin/env python3
"""Parse swemmoon.c and generate src/moshier/moon_tables.rs.

Usage: python3 scripts/gen_moshier_moon_tables.py

swemmoon.c has two #ifdef MOSH_MOON_200 blocks that each contain alternative
definitions for z[] and MB[].  We always want the #else branch (NMB=77,
25-element z[]).  The remaining arrays (LR, LRT, BT, LRT2, BT2) appear only
once, outside any ifdef.
"""

import re
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
C_SOURCE = SCRIPT_DIR / "../../swisseph/swemmoon.c"
OUTPUT = SCRIPT_DIR / "../src/moshier/moon_tables.rs"

# Expected element counts for validation
EXPECTED = {
    "LR": 944,  # 8 × 118
    "MB": 462,  # 6 × 77
    "LRT": 304,  # 8 × 38
    "BT": 80,  # 5 × 16
    "LRT2": 150,  # 6 × 25
    "BT2": 60,  # 5 × 12
    "Z": 25,
}

CONSTANTS = [
    ("NLR", 118),
    ("NMB", 77),
    ("NLRT", 38),
    ("NBT", 16),
    ("NLRT2", 25),
    ("NBT2", 12),
]

# (name, cols, rust_type, take_last)
SHORT_ARRAYS = [
    ("LR", 8, "i16", False),
    ("MB", 6, "i16", True),  # appears twice; want the #else version (NMB=77)
    ("LRT", 8, "i16", False),
    ("BT", 5, "i16", False),
    ("LRT2", 6, "i16", False),
    ("BT2", 5, "i16", False),
]


def read_source():
    with open(C_SOURCE) as f:
        return f.read()


def strip_comments(body):
    body = re.sub(r"/\*.*?\*/", "", body, flags=re.DOTALL)
    body = re.sub(r"//[^\n]*", "", body)
    return body


def extract_short_array(src, name, take_last=False):
    """Extract a static const short array by name.

    The C size expression may be an arbitrary expression (e.g. 8*NLR), so we
    match [^]]* instead of a numeric literal.
    """
    pattern = rf"static\s+const\s+short\s+{name}\s*\[[^\]]*\]\s*=\s*\{{(.*?)\}}\s*;"
    matches = list(re.finditer(pattern, src, re.DOTALL))
    if not matches:
        raise ValueError(f"Short array {name} not found in C source")
    m = matches[-1] if take_last else matches[0]
    body = strip_comments(m.group(1))
    tokens = [t.strip() for t in body.split(",") if t.strip()]
    return [int(t) for t in tokens]


def extract_double_array(src, name, take_last=False):
    """Extract a static const double array by name (size expression may be empty)."""
    pattern = rf"static\s+const\s+double\s+{name}\s*\[\s*\]\s*=\s*\{{(.*?)\}}\s*;"
    matches = list(re.finditer(pattern, src, re.DOTALL))
    if not matches:
        raise ValueError(f"Double array {name} not found in C source")
    m = matches[-1] if take_last else matches[0]
    body = strip_comments(m.group(1))
    tokens = [t.strip() for t in body.split(",") if t.strip()]
    return tokens  # keep as strings to preserve precision


def format_f64(val_str):
    """Format a C double literal for Rust."""
    s = val_str.strip()
    s = s.replace("E", "e")
    if "." not in s and "e" not in s:
        s += ".0"
    return s


def format_short_rows(values, per_line):
    rows = []
    for i in range(0, len(values), per_line):
        chunk = values[i : i + per_line]
        rows.append("    " + ", ".join(str(v) for v in chunk) + ",")
    return rows


def validate(src):
    """Check all element counts against expectations.  Returns True if all OK."""
    counts = {}
    for name, cols, _, take_last in SHORT_ARRAYS:
        counts[name] = len(extract_short_array(src, name, take_last))
    counts["Z"] = len(extract_double_array(src, "z", take_last=True))

    ok = True
    for key, expected in EXPECTED.items():
        actual = counts[key]
        status = "OK" if actual == expected else "MISMATCH"
        print(f"  {key:6s}: {actual:4d} elements  ({status}, expected {expected})")
        if actual != expected:
            ok = False
    return ok


def generate(src):
    out = []
    out.append(
        "// Generated by scripts/gen_moshier_moon_tables.py — do not edit by hand."
    )
    out.append("// Source: swemmoon.c (Moshier lunar coefficient tables)")
    out.append("")
    out.append("#![allow(clippy::unreadable_literal)]")
    out.append("#![allow(clippy::excessive_precision)]")
    out.append("")

    for cname, cval in CONSTANTS:
        out.append(f"pub const {cname}: usize = {cval};")
    out.append("")

    for name, cols, rust_type, take_last in SHORT_ARRAYS:
        values = extract_short_array(src, name, take_last)
        out.append(f"pub const {name}: [{rust_type}; {len(values)}] = [")
        out.extend(format_short_rows(values, cols))
        out.append("];")
        out.append("")

    z_values = extract_double_array(src, "z", take_last=True)
    out.append(f"pub const Z: [f64; {len(z_values)}] = [")
    for i in range(0, len(z_values), 4):
        chunk = z_values[i : i + 4]
        out.append("    " + ", ".join(format_f64(v) for v in chunk) + ",")
    out.append("];")
    out.append("")

    return "\n".join(out)


def main():
    if not C_SOURCE.exists():
        print(f"Error: C source not found at {C_SOURCE}", file=sys.stderr)
        sys.exit(1)

    src = read_source()

    print("Validating element counts...")
    if not validate(src):
        print("ERROR: element count mismatch — aborting", file=sys.stderr)
        sys.exit(1)

    output = generate(src)

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT, "w") as f:
        f.write(output)

    print(f"Generated {OUTPUT} ({len(output)} bytes)")


if __name__ == "__main__":
    main()
