#!/usr/bin/env python3
"""Parse swemptab.h and generate src/moshier/tables.rs.

Usage: python3 scripts/gen_moshier_tables.py
"""

import re
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
C_SOURCE = SCRIPT_DIR / "../../swisseph/swemptab.h"
OUTPUT = SCRIPT_DIR / "../src/moshier/tables.rs"

PLANETS = [
    ("mer", "MER"),
    ("ven", "VEN"),
    ("ear", "EAR"),
    ("mar", "MAR"),
    ("jup", "JUP"),
    ("sat", "SAT"),
    ("ura", "URA"),
    ("nep", "NEP"),
    ("plu", "PLU"),
]


def read_source():
    with open(C_SOURCE) as f:
        return f.read()


def extract_array(src, name, dtype):
    """Extract a C array by name. Returns list of values."""
    pattern = rf"static\s+(?:const\s+)?{dtype}\s+{name}\s*\[\s*\]\s*=\s*\{{(.*?)\}}\s*;"
    m = re.search(pattern, src, re.DOTALL)
    if not m:
        raise ValueError(f"Array {name} not found")
    body = m.group(1)
    # Strip C comments
    body = re.sub(r"/\*.*?\*/", "", body, flags=re.DOTALL)
    body = re.sub(r"//[^\n]*", "", body)
    tokens = [t.strip() for t in body.split(",") if t.strip()]
    if dtype == "double":
        return [t for t in tokens]  # keep as strings to preserve precision
    else:
        return [int(t) for t in tokens]


def extract_struct(src, name):
    """Extract a plantbl struct instance. Returns (max_harmonic[9], max_power_of_t, distance)."""
    pattern = rf"static\s+struct\s+plantbl\s+{name}\s*=\s*\{{(.*?)\}}\s*;"
    m = re.search(pattern, src, re.DOTALL)
    if not m:
        raise ValueError(f"Struct {name} not found")
    body = m.group(1)
    body = re.sub(r"/\*.*?\*/", "", body, flags=re.DOTALL)
    body = re.sub(r"//[^\n]*", "", body)

    # The struct has: { {h0,h1,...,h8}, max_t, name_args, name_tabl, name_tabb, name_tabr, distance }
    # Extract the inner brace for max_harmonic
    inner = re.search(r"\{([^}]+)\}", body)
    if not inner:
        raise ValueError(f"Cannot parse max_harmonic in {name}")
    harmonics = [int(x.strip()) for x in inner.group(1).split(",") if x.strip()]
    assert len(harmonics) == 9, f"{name}: expected 9 harmonics, got {len(harmonics)}"

    # Everything after the inner brace closing
    rest = body[inner.end() :]
    tokens = [t.strip() for t in rest.split(",") if t.strip()]
    # tokens[0] = max_power_of_t, then identifiers, then distance (last numeric)
    max_power = int(tokens[0])

    # Distance is the last token that looks numeric
    distance = None
    for t in reversed(tokens):
        try:
            float(t.replace("e", "E"))
            distance = t
            break
        except ValueError:
            continue
    if distance is None:
        raise ValueError(f"Cannot find distance in {name}")

    return harmonics, max_power, distance


def format_f64(val_str):
    """Format a C double literal for Rust."""
    s = val_str.strip()
    # Normalize exponent notation
    s = s.replace("E", "e")
    # Ensure it has a decimal point or exponent
    if "." not in s and "e" not in s:
        s += ".0"
    return s


def generate(src):
    lines = []
    lines.append("// Generated by scripts/gen_moshier_tables.py — do not edit by hand.")
    lines.append("// Source: swemptab.h (Moshier planetary coefficient tables)")
    lines.append("")
    lines.append("#![allow(clippy::unreadable_literal)]")
    lines.append("#![allow(clippy::excessive_precision)]")
    lines.append("")
    lines.append("use super::PlantTbl;")
    lines.append("")

    for short, upper in PLANETS:
        tabl = extract_array(src, f"{short}tabl", "double")
        tabb = extract_array(src, f"{short}tabb", "double")
        tabr = extract_array(src, f"{short}tabr", "double")
        args = extract_array(src, f"{short}args", r"signed\s+char")
        harmonics, max_power, distance = extract_struct(src, f"{short}404")

        # arg_tbl
        lines.append(f"const {upper}_ARG_TBL: [i8; {len(args)}] = [")
        chunk_size = 20
        for i in range(0, len(args), chunk_size):
            chunk = args[i : i + chunk_size]
            lines.append("    " + ", ".join(f"{v}" for v in chunk) + ",")
        lines.append("];")
        lines.append("")

        # lon_tbl
        lines.append(f"const {upper}_LON_TBL: [f64; {len(tabl)}] = [")
        for i in range(0, len(tabl), 4):
            chunk = tabl[i : i + 4]
            lines.append("    " + ", ".join(format_f64(v) for v in chunk) + ",")
        lines.append("];")
        lines.append("")

        # lat_tbl
        lines.append(f"const {upper}_LAT_TBL: [f64; {len(tabb)}] = [")
        for i in range(0, len(tabb), 4):
            chunk = tabb[i : i + 4]
            lines.append("    " + ", ".join(format_f64(v) for v in chunk) + ",")
        lines.append("];")
        lines.append("")

        # rad_tbl
        lines.append(f"const {upper}_RAD_TBL: [f64; {len(tabr)}] = [")
        for i in range(0, len(tabr), 4):
            chunk = tabr[i : i + 4]
            lines.append("    " + ", ".join(format_f64(v) for v in chunk) + ",")
        lines.append("];")
        lines.append("")

        # PlantTbl instance
        h_str = ", ".join(str(h) for h in harmonics)
        lines.append(f"pub const {upper}404: PlantTbl = PlantTbl {{")
        lines.append(f"    max_harmonic: [{h_str}],")
        lines.append(f"    max_power_of_t: {max_power},")
        lines.append(f"    arg_tbl: &{upper}_ARG_TBL,")
        lines.append(f"    lon_tbl: &{upper}_LON_TBL,")
        lines.append(f"    lat_tbl: &{upper}_LAT_TBL,")
        lines.append(f"    rad_tbl: &{upper}_RAD_TBL,")
        lines.append(f"    distance: {format_f64(distance)},")
        lines.append("};")
        lines.append("")

    # PLANETS array in C planets[] order
    names = [f"&{upper}404" for _, upper in PLANETS]
    lines.append(f"pub const PLANETS: [&PlantTbl; {len(PLANETS)}] = [")
    lines.append("    " + ", ".join(names) + ",")
    lines.append("];")
    lines.append("")

    return "\n".join(lines)


def main():
    if not C_SOURCE.exists():
        print(f"Error: C source not found at {C_SOURCE}", file=sys.stderr)
        sys.exit(1)

    src = read_source()
    output = generate(src)

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT, "w") as f:
        f.write(output)

    print(f"Generated {OUTPUT} ({len(output)} bytes)")


if __name__ == "__main__":
    main()
