#!/usr/bin/env python3
"""Parse C nutation tables and emit Rust const arrays.

Sources:
  - swenut2000a.h: IAU 2000A luni-solar (678) + planetary (687) tables
  - swephlib.c: IAU 1980 nutation terms (105 + 7 Herring corrections)

Output: src/nutation/data.rs
"""

import re
import sys
from pathlib import Path

SWISSEPH_DIR = Path(__file__).resolve().parent.parent.parent / "swisseph"
OUTPUT = Path(__file__).resolve().parent.parent / "src" / "nutation" / "data.rs"


def extract_array(text: str, name: str) -> list[int]:
    """Extract all integers from a C array declaration."""
    pattern = rf"(?:static\s+const\s+\w+\s+)?{name}\s*\[\s*\]\s*=\s*\{{(.*?)\}}\s*;"
    m = re.search(pattern, text, re.DOTALL)
    if not m:
        raise ValueError(f"Could not find array {name}")
    body = m.group(1)
    # Strip C comments
    body = re.sub(r"/\*.*?\*/", "", body, flags=re.DOTALL)
    body = re.sub(r"//[^\n]*", "", body)
    # Extract all integers (including negative)
    return [int(x) for x in re.findall(r"-?\d+", body)]


def extract_nt(text: str) -> list[int]:
    """Extract IAU 1980 nt[] array, stopping at ENDMARK."""
    pattern = r"static\s+const\s+short\s+nt\s*\[\s*\]\s*=\s*\{(.*?)ENDMARK"
    m = re.search(pattern, text, re.DOTALL)
    if not m:
        raise ValueError("Could not find nt[] array")
    body = m.group(1)
    body = re.sub(r"/\*.*?\*/", "", body, flags=re.DOTALL)
    body = re.sub(r"//[^\n]*", "", body)
    body = re.sub(r"#if\s+\d+", "", body)
    body = re.sub(r"#endif", "", body)
    return [int(x) for x in re.findall(r"-?\d+", body)]


def group(values: list[int], stride: int) -> list[list[int]]:
    """Group flat list into rows of `stride`."""
    if len(values) % stride != 0:
        raise ValueError(f"Length {len(values)} not divisible by stride {stride}")
    return [values[i : i + stride] for i in range(0, len(values), stride)]


def fmt_row_i16(row: list[int], width: int = 4) -> str:
    return ", ".join(f"{v:>{width}}" for v in row)


def fmt_row_i32(row: list[int], width: int = 11) -> str:
    return ", ".join(f"{v:>{width}}" for v in row)


def emit_rust(
    nls_rows: list[list[int]],
    cls_rows: list[list[int]],
    npl_rows: list[list[int]],
    icpl_rows: list[list[int]],
    nt_rows: list[list[int]],
) -> str:
    lines = []
    lines.append("// Generated by scripts/gen_nutation_data.py — do not edit by hand.")
    lines.append("// Sources: swenut2000a.h (IAU 2000A), swephlib.c (IAU 1980)")
    lines.append("")
    lines.append("#![allow(clippy::unreadable_literal)]")
    lines.append("")

    # Constants
    lines.append("/// 0.1 microarcsecond to degrees")
    lines.append("pub const O1MAS2DEG: f64 = 1.0 / 3600.0 / 10_000_000.0;")
    lines.append("")
    lines.append(f"pub const NLS_COUNT: usize = {len(nls_rows)};")
    lines.append("/// IAU 2000B uses the first 77 entries of NLS/CLS")
    lines.append("pub const NLS_2000B: usize = 77;")
    lines.append(f"pub const NPL_COUNT: usize = {len(npl_rows)};")
    lines.append(f"pub const NT_COUNT: usize = {len(nt_rows)};")
    lines.append("")

    # NLS
    lines.append("/// Luni-solar argument multipliers: [L, L', F, D, Om]")
    lines.append(f"pub const NLS: [[i16; 5]; {len(nls_rows)}] = [")
    for row in nls_rows:
        lines.append(f"    [{fmt_row_i16(row)}],")
    lines.append("];")
    lines.append("")

    # CLS
    lines.append("/// Luni-solar nutation coefficients, unit 1e-7 arcsec")
    lines.append("/// [lon_sin, lon_sin_t, lon_cos, obl_cos, obl_cos_t, obl_sin]")
    lines.append(f"pub const CLS: [[i32; 6]; {len(cls_rows)}] = [")
    for row in cls_rows:
        lines.append(f"    [{fmt_row_i32(row)}],")
    lines.append("];")
    lines.append("")

    # NPL
    lines.append(
        "/// Planetary argument multipliers: [L, L', F, D, Om, Me, Ve, E, Ma, Ju, Sa, Ur, Ne, pre]"
    )
    lines.append(f"pub const NPL: [[i16; 14]; {len(npl_rows)}] = [")
    for row in npl_rows:
        lines.append(f"    [{fmt_row_i16(row)}],")
    lines.append("];")
    lines.append("")

    # ICPL
    lines.append("/// Planetary nutation coefficients, unit 1e-7 arcsec")
    lines.append("/// [lon_sin, lon_cos, obl_sin, obl_cos]")
    lines.append(f"pub const ICPL: [[i16; 4]; {len(icpl_rows)}] = [")
    for row in icpl_rows:
        lines.append(f"    [{fmt_row_i16(row)}],")
    lines.append("];")
    lines.append("")

    # NT (IAU 1980)
    lines.append(
        "/// IAU 1980 nutation terms (105 regular + 7 Herring 1987 corrections)"
    )
    lines.append("/// [MM, MS, FF, DD, OM, LS, LS2, OC, OC2]")
    lines.append('/// LS/OC in 0.0001", LS2/OC2 in 0.00001"')
    lines.append(
        "/// Rows with MM >= 101: Herring corrections (101 = sin/cos, 102 = cos/sin swap)"
    )
    lines.append(f"pub const NT: [[i16; 9]; {len(nt_rows)}] = [")
    for row in nt_rows:
        lines.append(f"    [{fmt_row_i16(row, width=6)}],")
    lines.append("];")
    lines.append("")

    # Tests
    lines.append("#[cfg(test)]")
    lines.append("mod tests {")
    lines.append("    use super::*;")
    lines.append("")
    lines.append("    #[test]")
    lines.append("    fn array_lengths() {")
    lines.append(f"        assert_eq!(NLS.len(), {len(nls_rows)});")
    lines.append(f"        assert_eq!(CLS.len(), {len(cls_rows)});")
    lines.append(f"        assert_eq!(NPL.len(), {len(npl_rows)});")
    lines.append(f"        assert_eq!(ICPL.len(), {len(icpl_rows)});")
    lines.append(f"        assert_eq!(NT.len(), {len(nt_rows)});")
    lines.append("    }")
    lines.append("")

    # Spot checks — first and last of each array
    def spot_check(name: str, rows: list[list[int]], fmt_fn):
        lines.append("    #[test]")
        lines.append(f"    fn {name.lower()}_spot_check() {{")
        lines.append(f"        assert_eq!({name}[0], [{fmt_fn(rows[0])}]);")
        mid = len(rows) // 2
        lines.append(f"        assert_eq!({name}[{mid}], [{fmt_fn(rows[mid])}]);")
        lines.append(
            f"        assert_eq!({name}[{len(rows) - 1}], [{fmt_fn(rows[-1])}]);"
        )
        lines.append("    }")
        lines.append("")

    spot_check("NLS", nls_rows, lambda r: fmt_row_i16(r))
    spot_check("CLS", cls_rows, lambda r: fmt_row_i32(r))
    spot_check("NPL", npl_rows, lambda r: fmt_row_i16(r))
    spot_check("ICPL", icpl_rows, lambda r: fmt_row_i16(r))
    spot_check("NT", nt_rows, lambda r: fmt_row_i16(r, width=6))

    # Herring correction entries
    lines.append("    #[test]")
    lines.append("    fn nt_herring_corrections() {")
    lines.append(
        "        // Entries 105-111 are Herring 1987 corrections (flag 101 or 102)"
    )
    lines.append("        for row in &NT[105..112] {")
    lines.append(
        '            assert!(row[0] >= 101, "Herring rows should have flag >= 101");'
    )
    lines.append("        }")
    lines.append("        assert_eq!(NT[105][0], 101);")
    lines.append("        assert_eq!(NT[111][0], 102);")
    lines.append("    }")

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main():
    # Read C sources
    swenut_text = (SWISSEPH_DIR / "swenut2000a.h").read_text()
    swephlib_text = (SWISSEPH_DIR / "swephlib.c").read_text()

    # Parse arrays
    nls_flat = extract_array(swenut_text, "nls")
    cls_flat = extract_array(swenut_text, "cls")
    npl_flat = extract_array(swenut_text, "npl")
    icpl_flat = extract_array(swenut_text, "icpl")
    nt_flat = extract_nt(swephlib_text)

    nls_rows = group(nls_flat, 5)
    cls_rows = group(cls_flat, 6)
    npl_rows = group(npl_flat, 14)
    icpl_rows = group(icpl_flat, 4)
    nt_rows = group(nt_flat, 9)

    # Validate counts
    assert len(nls_rows) == 678, f"NLS: expected 678, got {len(nls_rows)}"
    assert len(cls_rows) == 678, f"CLS: expected 678, got {len(cls_rows)}"
    assert len(npl_rows) == 687, f"NPL: expected 687, got {len(npl_rows)}"
    assert len(icpl_rows) == 687, f"ICPL: expected 687, got {len(icpl_rows)}"
    assert len(nt_rows) == 112, f"NT: expected 112, got {len(nt_rows)}"

    # First/last spot checks against known C values
    assert nls_rows[0] == [0, 0, 0, 0, 1], f"NLS[0] mismatch: {nls_rows[0]}"
    assert nls_rows[-1] == [2, 0, 2, 4, 1], f"NLS[-1] mismatch: {nls_rows[-1]}"
    assert cls_rows[0] == [-172064161, -174666, 33386, 92052331, 9086, 15377]
    assert cls_rows[-1] == [-3, 0, 0, 2, 0, 0]
    assert npl_rows[0] == [0, 0, 0, 0, 0, 0, 0, 8, -16, 4, 5, 0, 0, 0]
    assert npl_rows[-1] == [0, 0, 2, 2, 2, 0, 0, 2, 0, -2, 0, 0, 0, 0]
    assert icpl_rows[0] == [1440, 0, 0, 0]
    assert icpl_rows[-1] == [3, 0, 0, -1]
    assert nt_rows[0] == [0, 0, 0, 0, 2, 2062, 2, -895, 5]
    assert nt_rows[-1] == [102, 0, 2, -2, 2, -118, 0, -47, 0]

    print(f"NLS:  {len(nls_rows)} rows OK")
    print(f"CLS:  {len(cls_rows)} rows OK")
    print(f"NPL:  {len(npl_rows)} rows OK")
    print(f"ICPL: {len(icpl_rows)} rows OK")
    print(f"NT:   {len(nt_rows)} rows OK")

    # Generate and write
    rust_code = emit_rust(nls_rows, cls_rows, npl_rows, icpl_rows, nt_rows)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(rust_code)
    print(f"\nWrote {OUTPUT} ({len(rust_code)} bytes)")


if __name__ == "__main__":
    main()
